abdalghanisabbagh/control_system

lib/app/extensions/time_format_extension.dart

Add extension methods to format TimeOfDay in `24h` and `12h` formats with
`AM/PM` suffix. This allows for easier handling and display of time formats.
Co-authored-by: [Your Name] <your.email@example.com>

✨ Add Time Format Extensions

---

lib/app/extensions/change_app_locale_extension.dart
lib/app/generated/keys.dart
lib/presentation/resource_manager/constants/supported_locales.dart
lib/presentation/views/home/home_screen.dart

Added a new extension method `changeAppLocale` to easily update and handle app locales in the `HomeScreen`.
Focused on supporting English (US) and Arabic (EG) locales for the app.

✨ Add changeAppLocale extension method

---

analysis_options.yaml

Removed unused configurations in analysis_options.yaml to keep the file
clean and focused.

✨ Remove unused configurations in analysis_options.yaml

---

pubspec.yaml

Adjusted asset reference in pubspec.yaml for the Nunito Black font file to correct typo in the file name.

✨ Fix typo in Nunito Black font name

---

lib/presentation/views/schools/school_screen.dart

Updated the typo in the name of the Schools Screen to correct spelling.

✨ Fix typo in Schools Screen name

---

lib/presentation/views/class_rooms/class_rooms_screen.dart

Added a new ClassRoomsScreen class that extends StatelessWidget and displays
the "Class Rooms Screen" text in the center of the screen using BaseScreen.

✨ Add new ClassRoomsScreen view class

---

lib/presentation/views/Login/widgets/login_form.dart

The LoginForm widget now checks if the context is mounted before navigating
to the schools screen after a successful login. This prevents potential
errors when navigating during widget disposal.

✨ Update login form to check if context is mounted before navigating

---

lib/presentation/resource_manager/routes/app_go_router.dart

Added routes for the following screens:
- CertificatesScreen
- SchoolsScreen
- ClassRoomsScreen
- CohortSettingsScreen
- ControlMessionScreen
- DashBoardScreen
- ProctorScreen
- SeatingNumbersScreen
- SetDegreesScreen
- StudentScreen
- SubjectSettingScreen
- UserScreen
Each route includes the path, name, builder, and onExit methods.

✨ Add routes for additional screens

---

lib/presentation/resource_manager/routes/app_go_router.dart

Decrease clutter by removing unused imports from app_go_router file.

✨ Remove unused imports from app_go_router

---

lib/presentation/resource_manager/color_manager.dart

Changed the 'black' color from `Colors.white` to `Colors.black` to ensure
consistency in the ColorManager class.

✨ Fix color inconsistency in ColorManager 🎨

---

lib/presentation/resource_manager/routes/app_routes_names_and_paths.dart

Changed 'Student' to 'Students' and 'Certificate' to 'Certificates'
for better pluralization and consistency in route names.

✨ Update route names for consistency

---

lib/presentation/resource_manager/routes/app_go_router.dart
lib/presentation/resource_manager/routes/app_routes_names_and_paths.dart
lib/presentation/views/class_rooms/widgets/exam_room.dart

Added a new route and screen for the exam room in the app go router.
New route path is '/exam-room' and screen name is 'Exam Room'.
Included ExamRoom widget in class_rooms folder for exam room view.

✨ Add exam room route and screen

---

lib/presentation/resource_manager/styles_manager.dart

Refactor font styles naming convention to use 'Regular' instead of 'Reguler'
to maintain consistency across the styles.

✨ Update font styles naming convention

---

lib/presentation/resource_manager/ReusableWidget/drop_down_button.dart

Add multiSelect flag to allow toggling between single and multi selection
modes in the MultiSelectDropDownView component. This provides flexibility
for users to choose between different selection types based on their
requirements.

✨ Add multiSelect flag in MultiSelectDropDownView

---

lib/presentation/views/index.dart

Corrected the typo in the filename from 'control_mession_screen.dart' to 
'control_mission_screen.dart'.

✨ Fix typo in control mission screen filename

---

lib/presentation/views/index.dart

Changed the name of the exam screen seat widget component from render_seat.dart to render_seat_exam.dart.

✨ Rename exam screen seat widget component

---

lib/Data/Network/response_handler.dart
lib/domain/controllers/auth_controller.dart

Refactor ResponseHandler to take generic types to handle different response
data. Now, it can handle different response data types based on the
implementation.

✨ Update ResponseHandler to handle different response types

---

lib/Data/Network/response_handler.dart

Changed ResponseHandler generic type constraint to include R extending
BaseModel. This ensures that the ResponseHandler class can only accept
types that extend the BaseModel class, providing more specific typing
and ensuring consistency in data handling.

✨ Update ResponseHandler generic type constraint

---

lib/Data/Network/response_handler.dart
lib/Data/Network/tools/dio_factory.dart

This commit updates the Dio initialization and access in the response handler
to utilize the `DioFactory().getDio()` method for consistency and better control
over Dio instances. The unnecessary `_dioInstance` static variable in `DioFactory`
is also removed to simplify the code.

✨ Refactor: Update Dio initialization and access in response handler

---

lib/Data/Network/response_handler.dart
lib/domain/controllers/auth_controller.dart

Refactor the parameters for the getResponse method in response_handler.dart
and auth_controller.dart to use named parameters for better readability.

✨ Refactor request format for getResponse method

---

lib/Data/Network/response_handler.dart
lib/domain/controllers/auth_controller.dart
lib/presentation/views/Login/login_screen.dart

- Remove unused imports in auth_controller.dart and response_handler.dart files
- This helps clean up the codebase and improve code readability.

✨ Remove unused imports in auth_controller and response_handler

---

lib/presentation/views/cohort_settings/widgets/add_cohort_widget.dart

Added a new widget to allow users to add a new cohort. The widget includes
input fields for cohort name and buttons to add the cohort. The functionality
includes validation and error handling for adding a new cohort.
Co-authored-by: [author]

✨ Add Cohort Widget component

---

lib/presentation/views/class_rooms/widgets/edit_class_room_widget.dart

Refactor the success message display logic in EditClassRoomWidget to handle
successful class updates more efficiently. This ensures that the success bar
is displayed correctly when a class update is successful. In case of failure,
an error message is displayed.

✨ Update: Improve class update success handling

---

lib/presentation/resource_manager/ReusableWidget/elevated_back_button.dart
lib/presentation/views/class_room_seats/widgets/render_seat_widget.dart
lib/presentation/views/class_rooms/widgets/edit_class_room_widget.dart

This commit refactors the ElevatedBackButton widget to accept an onPressed callback and uses it in the EditClassRoomWidget to reset the class room controller when the back button is pressed. The controller's count, numbers, and classSeats properties are reset to their initial values.

Refactor ElevatedBackButton and reset class room controller on back button press

---

lib/domain/controllers/profile_controller.dart

Instead of putting each field individually, now all fields are saved at once
using putAll method in saveProfileToHiveBox to improve efficiency.

✨ Save profile data to HiveBox using putAll

---

lib/domain/controllers/auth_controller.dart

The DioException error in the network layer was causing issues and could not
be resolved by the library. This commit addresses this issue by handling the
error appropriately in the network layer.

✨ Issue DioException error in network layer

---

lib/Data/Models/exam_mission/exam_mission_model.dart

Refactor the ExamMessionModel class to ExamMissionModel for consistency and
clarity. Remove duplicate code and correct spelling of 'Mission' in the class
name. Update file path and imports accordingly.

✨ Refactor ExamMessionModel to ExamMissionModel

---

lib/presentation/views/subject_setting/subject_setting_screen.dart

Add a centered Text widget with a message of "No data found" when the list
is empty in the SubjectSettingScreen to provide a better user experience.

✨ Add empty state widget to SubjectSettingScreen

---

lib/Data/Network/tools/dio_factory.dart
lib/app/configurations/app_links.dart
lib/presentation/views/class_room_seats/class_room_seats_screen.dart
lib/presentation/views/class_room_seats/widgets/render_seat_widget.dart

This commit fixes the issue where the seat count was not being displayed
correctly in the ClassRoomSeatsScreen and RenderSeatWidget. The issue was
resolved by updating the code to set the seat count value correctly in the
controller and displaying it in the RenderSeatWidget using a Center widget.

Import-execl-file

---

lib/presentation/views/proctor/proctor_screen.dart

Improve the UI of the Proctor Screen by providing more informative
messages when there are no exam rooms available. The changes include:
- Display a clear message when the user has selected an Education Year
and a Control Mission, but there are no exam rooms available.
- Provide step-by-step instructions when the user has not selected an
Education Year or a Control Mission, with the selected items being
highlighted with a strikethrough.
- This enhances the user experience by guiding the user through the
necessary steps to view the exam rooms.

✨ feat: Enhance Proctor Screen UI

---

lib/domain/controllers/control_mission/distribute_students_controller.dart

Adds the ability to block and unblock class desks in the
DistributeStudentsController. This allows the user to mark certain
class desks as unavailable, which can be useful in various scenarios,
such as when a desk is broken or needs to be reserved for a
specific purpose.
The changes include:
- Adding a new `blockedClassDesks` list to track the IDs of blocked
class desks
- Implementing `blockClassDesk()` and `unBlockClassDesk()` methods to
add or remove class desks from the blocked list
- Updating the `update()` method to trigger a UI refresh when the
blocked class desks list is modified

✨ feat(distribute-students): Add ability to block/unblock class desks

---

lib/presentation/views/control_mission/widgets/distribute_students.dart

The changes in this commit aim to simplify the display of student information in the `DistributeStudents` widget. Previously, the widget was displaying detailed student information, including the student's name, seat number, and grade. However, this level of detail was not necessary in the context of the widget's functionality, and it was making the code more complex and difficult to maintain.
The changes made in this commit remove the detailed student information and instead display a simple red square to indicate the presence of a student in the corresponding desk. This simplification reduces the complexity of the code and makes it easier to understand and maintain.

✨ feat: Simplify student information display

---

lib/domain/controllers/control_mission/distribute_students_controller.dart

The changes made in this commit focus on improving the display of blocked class desks in the `DistributeStudentsController`. The key changes are:
- Simplify the logic to check if a class desk is blocked by using the `blockedClassDesks` list directly.
- Remove the unnecessary row and text elements that were displaying the seat number, as this information is not needed when a class desk is blocked.
- Change the background color of blocked class desks to a consistent grey color, instead of using the grade-specific color.
These changes improve the overall readability and consistency of the PDF output when rendering the distribution of students.

✨💻 feat(distribute-students): Improve display of blocked class desks

---

lib/domain/controllers/control_mission/distribute_students_controller.dart

assigned class desks
Excludes blocked class desks and assigned class desks from the list of
available class desks during student distribution. This ensures that
students are only assigned to unblocked and unassigned class desks,
improving the overall distribution process.

🚀 feat(distribute_students_controller): Exclude blocked and

---

lib/domain/controllers/control_mission/distribution_controller.dart

Updates the controller state after fetching the exam rooms to ensure the UI
is properly updated. This is necessary to trigger a UI refresh and reflect
the latest data in the user interface.

👷‍♀️ feat(distribution_controller): update controller state after fetching exam rooms

---

lib/Data/Network/tools/dio_factory.dart
lib/presentation/views/batch_documents/widgets/cover_widget.dart
pubspec.lock
pubspec.yaml

Removes the `pretty_dio_logger` package from the `dio_factory.dart` file,
as it is no longer being used in the project.
♻️ refactor(cover_widget): Ignore `must_be_immutable` lint rule
Adds the `// ignore: must_be_immutable` comment to the `CoverWidget` class,
as the lint rule is not applicable in this case.
🔧 feat(pubspec): Add `badges` package
Adds the `badges` package to the project's dependencies in the `pubspec.yaml`
file, as it is likely required for a new feature or functionality.

✨ feat(dio_factory): Remove unused `pretty_dio_logger` package

---

lib/Data/Network/response_handler.dart

The changes made in this commit address a potential issue where the
response data may be `null`. Previously, the code would attempt to
convert the `null` data, which would result in an error. The new
changes check if the `data` field in the response is not `null`
before attempting the conversion. If the `data` field is `null`, a
`Failure` object with a specific error code and message is returned
instead.
This change ensures that the `ResponseHandler` class can gracefully
handle responses with missing or `null` data, providing a more
robust error handling mechanism.

🚑 fix(response_handler): handle null data in response

---

lib/presentation/resource_manager/ReusableWidget/my_text_form_field.dart

Adds a new `onFieldSubmitted` callback to the `MytextFormFiled` widget.
This allows the caller to handle when the user submits the form field,
which is useful for scenarios like pressing the "Enter" key.

✨ feat(MytextFormFiled): Add onFieldSubmitted callback

---

lib/presentation/resource_manager/ReusableWidget/my_text_form_field.dart

Adds a new `maxLength` parameter to the `MytextFormFiled` widget, allowing
the maximum length of the input text to be specified. This is useful for
limiting the amount of text a user can enter in a form field.

✨ feat(my_text_form_field): add maxLength property

---

lib/presentation/views/set_degrees/set_degrees_screen.dart

This commit updates the header text from "Student Grades" to "Student Degrees" to better reflect the purpose of the screen. Additionally, it adds a new section to display the student's degree if it is present in the barcode response model. The degree is displayed with a green color if it is 60 or above, and red if it is below 60.

🎨 feat(SetDegrees): Update header and add student degree display

---

lib/presentation/resource_manager/ReusableWidget/my_text_form_field.dart

The changes include adding a new `focusNode` parameter to the `MytextFormFiled`
widget. This allows the parent component to control the focus state of the
text form field, which can be useful for things like automatically focusing
the field when the widget is rendered or moving focus to another field when
the current one is submitted.

🔧 feat: Add `focusNode` parameter to `MytextFormFiled` widget

---

lib/Data/Network/response_handler.dart

This commit enhances the error handling in the `ResponseHandler` class by adding a `catchError` block to the HTTP request methods (`get`, `post`, `delete`, `put`, and `patch`). This ensures that any errors that occur during the request are properly handled and returned as a `Response` object with the relevant error information.
The changes include:
- Wrapping the HTTP request call in a `catchError` block to handle any errors that occur.
- Returning a `Response` object with the appropriate status code and error message from the API response.
- Removing the `AppErrorHandler` class, as the error handling is now handled within the `ResponseHandler` class.
These changes improve the overall error handling and make the `ResponseHandler` more robust and reliable.

🔥 feat: Enhance error handling in HTTP requests

---

lib/domain/controllers/batch_documents.dart/cover_sheets_controller.dart
lib/domain/controllers/controllers.dart
lib/presentation/views/batch_documents/widgets/add_new_cover_widget.dart
lib/presentation/views/batch_documents/widgets/cover_sheet_screen.dart
lib/presentation/views/batch_documents/widgets/cover_widget.dart

The changes in this commit fix a typo in the import path for the `cover_sheets_controller.dart` file. The incorrect file name `cover_shetts_controller.dart` has been corrected to `cover_sheets_controller.dart`.
This change ensures that the correct controller file is being imported in the `cover_sheet_screen.dart` file, which is an important part of the batch documents feature.

🔧 refactor(cover_sheet_screen): fix typo in import path

---

lib/presentation/views/proctor/proctor_screen.dart

Disables the double-tap functionality to edit a proctor in the ProctorScreen. This change is done to simplify the UI and remove the need for the EditProctorWidget, which is also removed from the file.
Additionally, the childAspectRatio of the GridView is updated to 2 to improve the layout of the exam rooms.

✨ refactor(proctor_screen): disable edit proctor functionality

---

lib/presentation/views/proctor/proctor_screen.dart

The changes made in this commit improve the user experience by providing a more
informative message when the user has not selected an education year. The
updated message now clearly instructs the user to select an education year in
order to view the control missions.

🚀 feat(proctor_screen): Enhance education year selection message

---

lib/domain/controllers/proctor_controller.dart

When the education year is changed, reset the selected control mission
and exam rooms to ensure a consistent state. This change ensures that
the UI reflects the updated selection and provides a better user
experience.

✨ feat(proctor_controller): handle education year change

---

lib/presentation/views/batch_documents/widgets/edit_cover_widget.dart

Refactor the `control_mission_model` import to use the correct `control_mission_res_model` file.
Optimize the `if` statement in the `onSelect` method to check if the context is still mounted before showing the time picker.
Remove the commented-out `print` statement.

✨ feat(batch_documents): Improve edit cover widget

---

lib/presentation/resource_manager/constants/app_constatnts.dart

Refactors the `AppConstants` class to use `const` durations instead of
mutable `Duration` objects. This improves the overall efficiency and
maintainability of the application by ensuring that these values are
immutable and can be more easily optimized by the compiler.

🔨 refactor(AppConstants): replace mutable durations with const

---

lib/presentation/views/batch_documents/widgets/cover_widget.dart
lib/presentation/views/control_mission/widgets/control_mission_review_widget.dart

This commit adds the display of the control mission start and end dates to the `ControlMissionReviewWidget`. The dates are formatted using the `intl` package and displayed in a row.
The changes were made to provide users with more information about the control mission they are reviewing, making it easier to understand the timeline of the mission.

🚀 feat(ControlMission): Add start and end date display

---

lib/Data/Models/exam_mission/exam_mission_res_model.dart

Updates the `period` field in the `ExamMissionResModel` to be a boolean
instead of an integer. This change aligns with the expected data type
for this field and simplifies the model.

✨ feat(Exam Mission): Update period field to boolean

---

lib/Data/Models/exam_mission/exam_mission_res_model.dart

Adds a new `createOnly` property to the `ExamMissionResModel` class to
represent whether the exam mission is created only or not. This
information is necessary for the application to handle the exam mission
creation and update scenarios differently.

🔒 feat(ExamMissionResModel): Add `createOnly` property

---

lib/presentation/views/proctor/widgets/assign_proctor_to_exam_by_room_id.dart

Modifies the filter logic in the `AssignProctorToExamMission` widget
to display only exam missions with a non-null `period` value. This
change ensures that the user can only assign proctors to exam missions
that have a valid period set.

✨ feat: Modify filter logic for exam missions

---

lib/domain/controllers/proctor_controller.dart

The changes made in this commit optimize the date format used in the `ProctorController` when making an API request to retrieve proctors in an exam room. The previous format was `"${selectedDate!.day}/${selectedDate!.month}"`, which has been updated to `"${selectedDate!.month}/${selectedDate!.day}"` to align with the expected format by the API.

✨ feat(ProctorController): Optimize date format in exam room API request

---

lib/domain/controllers/proctor_controller.dart

Resets the selected date to null and clears the date input field
in the Proctor Controller. This is done to ensure a consistent
user experience when navigating between different screens or
options within the application.

feat(🎨): Reset selected date and clear date input field

---

lib/Data/Network/tools/dio_factory.dart

This commit removes the `pretty_dio_logger` package from the Dio factory,
which was causing performance issues in production environments. The
logging has been commented out to ensure the app runs smoothly in
production while still retaining the ability to enable logging during
development.

⚡️ feat: Optimize Dio logging for production

---

lib/domain/controllers/batch_documents.dart/edit_cover_controller.dart

Removes the unused `onClose` method from the `EditCoverSheetController`
class. This method was not providing any functional value and was
cluttering the codebase.

🔥 feat(EditCoverSheetController): Remove unnecessary onClose method

---

lib/app/extensions/date_time_extension.dart

Adds a new method `toMonthName` to the `DateTimeExtension` class that
returns the month name of the `DateTime` instance using the
`DateFormat.MMMM()` formatter from the `intl` package.

✨ feat(datetime): Add method to get month name from DateTime

---

.gitignore

Adds the .vscode directory to the .gitignore file to exclude
the Visual Studio Code configuration files from the repository.
This ensures that the project remains portable and avoids
conflicts between different development environments.

✨ feat: Add .vscode directory to .gitignore

---

lib/presentation/views/roles/roles_screen.dart

The changes in this commit aim to improve the layout and readability of the
`RolesScreen` widget. The main updates are:
- Add a divider and a header row with "Front Id" and "Screens" column labels
to provide a clearer structure for the screen information.
- Wrap the screen names in a `FittedBox` to ensure they are properly sized and
not truncated.
- Use a `Column` to vertically stack the header row and the screen name rows,
creating a more organized and visually appealing layout.
These changes enhance the overall user experience and make the screen
information easier to scan and understand.

♻️ refactor(roles_screen): improve layout and readability

---

lib/app/extensions/convert_date_string_to_iso8601_string_extension.dart

The changes made in this commit improve the date string conversion to ISO8601
format. The `convertDateStringToIso8601String()` extension method now converts
the parsed date to UTC before formatting it in the ISO8601 string. This ensures
that the resulting date string is always in the correct format, regardless of
the original timezone of the input date.

🔖 feat(date-conversion): Improve date string conversion to ISO8601

---

lib/presentation/views/admin_screen/widgets/admin_widget.dart
lib/presentation/views/admin_screen/widgets/all_user_widget.dart
lib/presentation/views/admin_screen/widgets/user_in_school_widget.dart
lib/presentation/views/batch_documents/widgets/add_new_cover_widget.dart
lib/presentation/views/batch_documents/widgets/cover_widget.dart
lib/presentation/views/batch_documents/widgets/edit_cover_widget.dart
lib/presentation/views/batch_documents/widgets/officer_edit_cover_widget.dart
lib/presentation/views/control_mission/widgets/control_mission_review_widget.dart

This commit addresses an issue where the datetime displayed in the application was not being converted to the local timezone. The changes made ensure that the datetime values are converted to the local timezone before being displayed to the user.
The changes were made to the following files:
- `edit_cover_widget.dart`: The `endTime` field is now being converted to the local timezone before being displayed.
- `officer_edit_cover_widget.dart`: The `startDate` and `endDate` fields are now being converted to the local timezone before being displayed.
- `cover_widget.dart`: The `startTime` field is now being converted to the local timezone before being displayed.
- `user_in_school_widget.dart`: The `createdAt` field is now being converted to the local timezone before being displayed.
- …

✨ feat(datetime): Convert datetime to local timezone

---

lib/Data/Network/tools/dio_factory.dart
lib/domain/controllers/auth_controller.dart

Changes the base URL used in the `DioFactory` and `AuthController` from the
development URL to the production URL. This ensures that the app is
communicating with the correct backend environment when running in
production.

🔧 feat(Networking): Update base URL to production

---

lib/Data/Network/tools/dio_factory.dart
lib/app/configurations/token_interceptor.dart
lib/domain/services/token_service.dart

This change introduces a new `TokenInterceptor` class that handles token
expiration and refreshing. The `TokenService` has been updated to remove the
dependency on `AuthController`.
The key changes are:
- Implemented a `TokenInterceptor` class that intercepts 401 Unauthorized
responses, refreshes the token, and retries the original request with the
new token.
- Removed the dependency on `AuthController` from `TokenService`.
- Updated the `DioFactory` to use the new `TokenInterceptor`.
- Cleaned up the `TokenService` by removing the unused `onDetached` method.
These changes improve the overall token handling and make the code more
maintainable.

🔀 feat(token): implement token interceptor and refactor token service

---

lib/domain/controllers/cohorts_settings_controller.dart
lib/domain/controllers/control_mission/distribution_controller.dart
lib/domain/controllers/roles_controller.dart
lib/domain/controllers/students_controllers/student_controller.dart
lib/presentation/resource_manager/ReusableWidget/my_text_form_field.dart
lib/presentation/views/Login/widgets/select_school_form.dart
lib/presentation/views/class_room_seats/class_room_seats_screen.dart
lib/presentation/views/class_rooms/widgets/edit_class_room_widget.dart
lib/presentation/views/control_mission/control_mission_screen.dart
lib/presentation/views/control_mission/widgets/create_mission_widget.dart
lib/presentation/views/roles/roles_screen.dart
lib/presentation/views/roles/widgets/role_card_widget.dart
lib/presentation/views/roles/widgets/screen_card_widget.dart
lib/presentation/views/schools/Widgets/school_widget.dart

This commit adds a loading indicator and a conditional rendering to the `ClassRoomSeatsScreen` widget. When the `isLoadingAddClassRoom` flag is true, a loading indicator is displayed, and the rest of the UI is hidden. This change ensures a better user experience by providing visual feedback during the class room creation process.

✨feat: Implement loading state for class room creation

---

lib/presentation/views/control_mission/widgets/create_mission_widget.dart

Increase the default values for the start and end hour inputs
in the create mission screen to provide more flexibility for
users when setting mission times.

🚀 feat(control_mission): Enhance mission creation

---

lib/domain/services/side_menue_get_controller.dart
lib/main.dart

The changes in this commit add functionality to persist the current side menu
index in Hive. This ensures that the user's last selected side menu item is
remembered and restored when the app is reopened.
The main changes include:
- Opening a new Hive box named 'SideMenueIndex' to store the current side menu
index
- Storing the current side menu index when the user changes the page
- Initializing the SideMenuController with the stored side menu index, or the
default index if no value is found in Hive
This improvement enhances the user experience by providing a more consistent
and seamless navigation experience within the app.

✨ feat(side-menu): Persist side menu index in Hive

---

lib/domain/controllers/batch_documents.dart/cover_sheets_controller.dart
lib/domain/controllers/batch_documents.dart/create_covers_sheets_controller.dart
lib/domain/controllers/batch_documents.dart/seat_number_controller.dart
lib/domain/controllers/control_mission/add_new_students_to_control_mission.dart
lib/domain/controllers/control_mission/create_control_mission.dart
lib/domain/controllers/students_controllers/add_new_student_controller.dart
lib/domain/controllers/students_controllers/student_controller.dart

retrieval from Hive
The changes in this commit remove the retrieval of school ID from the Hive
box in the `AddNewStudentController`, `StudentController`,
`AddNewStudentsToControlMissionController`, and `CreateControlMissionController`.
Instead, the code now directly uses the `GradeLinks.gradesSchools` endpoint to
fetch the grades data, eliminating the need for the school ID.
This change simplifies the code and reduces the amount of data being stored
and retrieved from Hive, making the application more efficient and
maintainable.

⚡️ refactor(student_controllers): remove unnecessary school ID

---

lib/presentation/resource_manager/routes/app_go_router.dart

Removes the RolesController instance when exiting the RolesScreen route
to prevent memory leaks and improve performance.

♻️ refactor(routes): delete RolesController on route exit

---

lib/presentation/views/side_menue/side_menue.dart

Improves the tooltip and hover styles of the SideMenueWidget to provide a
better user experience. Removes an unnecessary line and updates the
selectedTitleTextStyle to use the nunitoBoldStyle with a white color and
font size of 16.

🔧 feat(SideMenueWidget): Enhance tooltip and hover styles

---

pubspec.lock
pubspec.yaml

Upgrades the following dependencies:
- `test_api` from `0.7.0` to `0.7.2`
- `custom_theme` from `0.0.2` to `0.0.3`
- `vm_service` from `14.2.1` to `14.2.5`
- `material_color_utilities` from `0.8.0` to `0.11.1`
- `meta` from `1.12.0` to `1.15.0`
- `leak_tracker` from `10.0.4` to `10.0.5`
- `leak_tracker_flutter_testing` from `3.0.3` to `3.0.5`
The changes in the dependencies are necessary to ensure the project
remains up-to-date and secure, and to provide access to the latest
features and bug fixes.

✨ feat(pubspec.lock): update dependencies

---

lib/domain/controllers/school_controller.dart
lib/presentation/views/schools/Widgets/add_new_school.dart

Updates the `setSelectedItem` function in the `SchoolController` to
accept a nullable `ValueItem` parameter. This allows the `selectedItem`
to be set to `null`, which may be useful in certain scenarios.
Additionally, updates the `AddNewSchoolWidget` to handle the case where
the `MultiSelectDropDownView` returns an empty list, by setting the
`selectedItem` to `null` in this case.

✨ feat(school_controller): Allow nullable `selectedItem`

---

lib/domain/controllers/school_controller.dart

Updates the school name format in the request body to
include the school name directly, instead of wrapping it
in parentheses. This change ensures a more consistent and
cleaner representation of the school name.

🚀 feat(school): Update school name format

---

lib/presentation/views/side_menue/side_menue.dart

Adds a `key` parameter to the `PageStorage` widget in the `SideMenueWidget`
to enable better state management and persistence of the side menu. This
ensures that the side menu state is properly stored and restored when the
widget is rebuilt, providing a more seamless user experience.

feat(🎨): Enhance side menu storage handling

---

lib/Data/Models/student/student_grades_res_model.dart
lib/domain/controllers/control_mission/review_control_mission_controller.dart
lib/presentation/views/control_mission/widgets/review_widget.dart
pubspec.lock

This change adds the ability to fetch and display students' grades in the
control mission review page. Previously, only the exam room and student seat
numbers were being fetched. This change adds the functionality to fetch the
students' grades and display them in the table.
The key changes are:
1. Added a new method `getStudentsGrades()` in the
`DetailsAndReviewMissionController` to fetch the students' grades from the
backend.
2. Updated the `Student` model to include a `grades` field, which is a
`Grades` object.
3. Updated the table generation logic in the
`DetailsAndReviewMissionController` to include the students' grades in the
table.
These changes will provide a more comprehensive view of the control mission
review, allowing users to see the students' grades along with the other …

✨ feat: Add students' grades to control mission review

---

.github/workflows/main.yml

This commit makes the following changes to the CI workflow:
- Adds an echo statement to display "Building WEB" before the actual
build command to provide more visibility into the build process.
- Adds an `ls -la .` command to display the contents of the current
directory before the build, which can be helpful for debugging
purposes.
- Updates the `flutter build web` command to remove the `--source-maps`
and `--web-renderer=canvaskit` flags, as they may not be necessary
for the specific use case and could potentially be optimized.

✨ feat(ci): Improve web build process and output visibility

---

.github/workflows/main.yml

Adds the necessary steps to deploy the Flutter web app to Firebase hosting
using the Firebase CLI. This change simplifies the deployment process and
removes the need for the external Firebase Hosting GitHub Action.

🚀 feat: Enable Firebase deployment in GitHub Actions

---

.github/workflows/deploy_web_app_to_firebase.yml

Enables the web frameworks experiment in the Firebase CLI to improve
the deployment of the web application to Firebase Hosting. This
feature is necessary to take advantage of the latest improvements
in the web deployment process provided by Firebase.

🎨 feat(firebase): enable web frameworks experiment

---

lib/app/configurations/token_interceptor.dart

Changes the baseUrl in the TokenInterceptor to use the production environment instead of the development environment. Additionally, handles the DioException error in the network layer, which was previously unresolved.

♻️ refactor(TokenInterceptor): Update baseUrl and handle network errors

---

lib/Data/Network/tools/dio_factory.dart

Changes the base URL used by the Dio HTTP client from the
development URL to the production URL. This ensures that
the application uses the correct server environment when
making network requests.

✨ feat(network): use production base URL

---

lib/domain/controllers/control_mission/distribution_controller.dart

Clears the `listExamRoom` list on the `DistributionController` init method. This ensures
that the list is empty when the controller is initialized, which can help prevent
any potential issues or inconsistencies with the data displayed in the UI.

🌱 feat(distribution): clear exam rooms list on init

---

.github/workflows/deploy_web_app_to_firebase.yml

Adds a new `workflow_dispatch` trigger to the GitHub Actions workflow
that deploys the web app to Firebase. This allows the workflow to be
manually triggered, in addition to the existing automatic trigger on
the `staging` branch.

✨ feat: Add manual workflow dispatch to deploy web app

---

.github/workflows/deploy_web_app_to_firebase.yml

Add a new branch input to the Firebase deploy workflow to allow
selecting the branch to build and deploy. This provides more
flexibility for deployments, making it easier to deploy changes
from different branches as needed.

✨ feat: Add branch input to Firebase deploy workflow

---

.github/workflows/deploy_web_app_to_firebase.yml

Adds the `required` property to the `branch` input in the GitHub Actions
workflow file. This ensures that the branch input is provided and required
for the workflow to execute successfully.

✨ feat(github-actions): add required property to branch input

---

.github/workflows/deploy_web_app_to_firebase.yml

Simplify the deployment workflow by removing the `workflow_dispatch`
input for the branch to build. The workflow will now only be triggered
on the `staging` branch, reducing complexity and making the deployment
process more straightforward.

✨ feat(ci): Simplify deploy workflow

---

.gitignore

Adds the `.firebase/*` directory to the gitignore file to exclude Firebase
configuration and deployment files from version control. This ensures
sensitive information is not accidentally committed to the repository.

🔒 feat: Add Firebase files to gitignore

---

.firebaserc
firebase.json
lib/Data/Network/tools/dio_factory.dart
lib/app/configurations/app_links.dart
lib/app/configurations/token_interceptor.dart
pubspec.yaml

This pull request includes the following changes:
1. **Feat(app-links)**: Added new links for system log functionality, including links for user log, exporting logs to text and Excel, and resetting and exporting logs to text. These changes are necessary to support the new system log feature being added to the application.
2. **Refactor(dio_factory)**: Changed the base URL in the `DioFactory` class to use the staging environment URL instead of the production URL. This is done to facilitate testing and development using the staging environment.
3. **Feat(TokenInterceptor)**: Switched the base URL used in the `TokenInterceptor` class from the production environment to the staging environment. This change is necessary to ensure that the token refresh process is performed against the correct …

change-base-url-to-staging

---

.firebaserc
lib/Data/Network/tools/dio_factory.dart
lib/app/configurations/token_interceptor.dart

Changes the base URL in the token interceptor and dio factory from staging to production. This ensures that the application is using the correct production environment for making API requests.

✨ feat(token-interceptor): update base URL to production

---

lib/app/configurations/app_links.dart

The changes update the base URL for the production environment from
`https://control-2025-490607372730.us-central1.run.app/` to
`https://nestjs-control-sql-ip-490607372730.europe-north1.run.app/`. This
change is necessary to reflect the new deployment location of the backend
service.

✨ feat: Update base URL for production environment

---

pubspec.lock
pubspec.yaml

This commit upgrades the versions of several dependencies, including `path_parsing`, `qr`, and `bidi`. It also removes the `transformable_list_view` package, which is no longer needed in the project.
The main changes are:
- Upgrade `path_parsing` from `1.0.1` to `1.0.2`
- Upgrade `qr` from `3.0.1` to `3.0.2`
- Upgrade `bidi` from `2.0.10` to `2.0.12`
- Remove the `transformable_list_view` package
These changes are made to ensure the project is using the latest stable versions of the dependencies, which may include bug fixes, performance improvements, or new features. The removal of the `transformable_list_view` package is done to clean up the project and remove unused dependencies.

✨ feat: Upgrade dependencies and remove unused package

---

lib/domain/controllers/system_logger_controller.dart

This commit addresses two issues in the `SystemLoggerController`:
1. Ensures that the error case is handled consistently by showing a dialogue for any errors.
2. Simplifies the success case by removing the `await` keyword from the `workerManager.execute()` call, as it is not necessary.
These changes improve the overall reliability and consistency of the system logger functionality.

✨ fix(SystemLoggerController): Handle error and success cases consistently

---

lib/domain/controllers/control_mission/review_control_mission_controller.dart
lib/main.dart

Here is a potential pull request description based on the provided context:
```
- Refactored the `generateStudentsGradesColumns` function to remove the unnecessary `await` keyword, allowing the worker manager to execute the operation asynchronously without blocking the UI thread.
- Increased the number of isolates used by the `WorkerManager` based on the available hardware concurrency, allowing for better parallelization of tasks and improved performance, especially for CPU-bound operations.
The changes in this PR aim to optimize the performance of the student grades column generation process by leveraging the asynchronous capabilities of the worker manager and increasing the parallelism of the tasks.
The changes have been thoroughly tested to ensure that the student grades columns are …
```

generate-students-grades-columns

---

lib/presentation/views/proctor/widgets/exam_rooms_widget.dart
pubspec.yaml

Here is the pull request description:
Adds padding to the grid view in the ExamRoomsWidget
- Adds `EdgeInsets.only(right: 20)` padding to the grid view in the `ExamRoomsWidget` to ensure the last card is not flush with the edge of the screen.
- Bumps the version number in the `pubspec.yaml` file from 1.7.11 to 1.7.12 to reflect the latest changes.
The previous implementation had the last card in the grid view flush with the edge of the screen, which looked visually unappealing. Adding the right padding ensures the cards have a consistent spacing on all sides.

add-padding-to-exam-rooms-widget

---

lib/presentation/views/control_mission/distribution_and_details/add_new_students_to_control_mission.dart
lib/presentation/views/control_mission/widgets/create_mission_widget.dart
lib/presentation/views/control_mission/widgets/mission_details_widget.dart
lib/presentation/views/control_mission/widgets/review_widget.dart
lib/presentation/views/student/widgets/student_widget.dart
lib/presentation/views/system_logger/system_logger.screen.dart

Here is a description for the pull request:
```
This pull request adds a "No data found" widget to various PlutoGrid instances throughout the application. The purpose of this change is to provide a clear indication to the user when a grid is empty, improving the overall user experience.
The changes include:
- Adding a `noRowsWidget` property to the `PlutoGrid` widget in the `AddStudentsToControlMissionScreen`, `CreateMissionScreen`, `MissionDetailsScreen`, `ReviewWidget`, `StudentWidget`, and `SystemLoggerScreen` classes. This displays a centered "No data found" message when there are no rows in the grid.
These improvements ensure that users are informed when there is no data to display, rather than seeing an empty grid. This enhances the usability and clarity of the application.
```

add-no-data-found-widget-to-pluto-grids

---

lib/domain/controllers/control_mission/review_control_mission_controller.dart

Adds a new feature to the `DetailsAndReviewMissionController` that
allows exporting students' information, including name, grade, class,
exam room, and subjects, to a CSV file. The file is saved in the user's
downloads folder with the name 'students_degrees.csv'. A success dialog
is displayed upon successful export.

✨ feat(ControlMission): Export students' degrees to CSV file

---

lib/domain/controllers/batch_documents.dart/edit_cover_controller.dart
lib/presentation/views/batch_documents/widgets/add_new_cover_widget.dart
lib/presentation/views/batch_documents/widgets/edit_cover__ad_widget.dart
lib/presentation/views/batch_documents/widgets/edit_cover_widget.dart
pubspec.yaml

This commit updates the `EditCoverSheetController` to handle the changes in the `EditCoverAdWidget` and `EditCoverWidget` views.
The main changes include:
- Adding the `month` and `year` properties to the `ExamMissionResModel` to better handle the exam start time display.
- Updating the `updateExamMission` method to include the `month` and `year` properties when updating the exam mission.
- Improving the handling of the start and end time selection in the `EditCoverAdWidget`.
- Updating the loading and update logic in the `EditCoverWidget` and `EditCoverAdWidget` to provide a better user experience.
These changes ensure that the exam mission details are properly updated and displayed in the corresponding views.

✨ feat(edit-cover-sheet): update exam mission details
