lib/app/main_app.dart, lib/main.dart
Reorganized MainApp widget structure for better readability and clarity. Including moving MainApp widget definition to a separate file for separation of concerns.
=> ✨ Refactor widget structure in MainApp

lib/app/main_app.dart, lib/domain/bindings/home_bindings.dart, lib/domain/controllers/home_controller.dart, lib/presentation/home/home_screen.dart, pubspec.lock, pubspec.yaml
- Added Get package to manage state more efficiently
- Updated MainApp to GetMaterialApp for state management
- Created HomeScreen with GetView for better state handling
- Added HomeBindings to bind HomeController for improved state management
=> ✨ Add Get package to improve state management in the app

lib/presentation/views/home/home_screen.dart
Changed the title from 'HomeScreenScreen' to 'HomeScreen' for clarity and
consistency.
=> ✨ Refactor: Update HomeScreen title

lib/app/main_app.dart, lib/presentation/resource_manager/routes/app_routes_names_and_paths.dart, lib/presentation/resource_manager/routes/go_router.dart
- Import GoRouter in main_app.dart
- Update GetMaterialApp to GetMaterialApp.router
- Add AppRoutesNamesAndPaths class with home screen paths
- Implement AppGoRouter with route configuration
=> ✨ Add new routes and GoRouter implementation

lib/domain/indices/home_index.dart, lib/presentation/resource_manager/routes/go_router.dart, lib/presentation/resource_manager/routes/index.dart
Export the home_bindings.dart and home_controller.dart files from the home_index.dart file in the domain/indices directory.
=> ✨ Export required files from home_index

lib/presentation/resource_manager/color_manager.dart, lib/presentation/resource_manager/font_manager.dart, lib/presentation/resource_manager/styles_manager.dart, lib/presentation/resource_manager/theme_manager.dart, lib/presentation/resource_manager/values_manager.dart, macos/Flutter/GeneratedPluginRegistrant.swift, pubspec.lock, pubspec.yaml
Added color, font, style, and theme managers to manage colors, fonts, text styles, and themes in the application. This will help maintain consistency and ease of theming across the app.
=> Add color, font, style, and theme managers

lib/app/extensions/device_type_extension.dart, lib/presentation/resource_manager/app_responsive.dart, lib/presentation/resource_manager/enums/device_type_enum.dart
- Added DeviceTypeExtension to determine device type based on width
- Added DeviceTypeEnum for mobile, tablet, and desktop
- Added AppResponsive widget for responsive UI rendering
=> 🔧 Add device type extension and AppResponsive widget

lib/app/main_app.dart, lib/presentation/resource_manager/routes/app_go_router.dart, lib/presentation/resource_manager/routes/app_routes_names_and_paths.dart, lib/presentation/resource_manager/routes/index.dart
Reorganized router setup to use a new class AppGoRouter for handling
routing in the application. Removed redundant code in go_router.dart
and updated references to new implementation. Updated homeScreenName
to be lowercase 'home' for consistency.
=> ✨ Refactor router setup to use AppGoRouter

lib/app/main_app.dart, lib/main.dart, lib/presentation/resource_manager/styles_manager.dart, lib/presentation/resource_manager/theme_manager.dart
Refactor font logic in styles_manager.dart to remove unused code and adjust
font styles. Update theme styles in theme_manager.dart by adding comment
documentation for better clarity and organization. Fix margin setting in
cardTheme and update border styles in getApplicationTheme to include
documentation. Update main_app.dart to initialize ScreenUtil and set the
application theme. Update main.dart to ensure screen size before running the
app.
=> ✨ Adjust font and theme styles

lib/app/extensions/time_format_extension.dart
- Added a new extension method `formatTime24h` to get the time in `24h` format
- Improved the code readability and reusability
=> ✨ Add Time Format Extension for 24h time format

lib/presentation/resource_manager/ReusableWidget/my_text_form_field.dart
Added a new reusable text form field component for inputs with specific
formatting requirements such as price inputs. This component includes
validation, controller, max lines, and optional suffix icon support.
=> ✨ Add reusable text form field component

lib/presentation/resource_manager/ReusableWidget/customized_button.dart
Added a new CustomizedButton component to create customizable buttons with different styles and functionalities.
=> ✨ Add CustomizedButton component

lib/presentation/resource_manager/validations.dart
Add methods to validate email and password fields in the Validations class
to ensure they meet specific criteria for email and password validation.
=> ✨ Add email and password validations to Validations

lib/presentation/resource_manager/ReusableWidget/drop_down_button.dart
Removed unnecessary ignore_for_file directive in drop_down_button.dart file.
=> ✨ refactor: Remove unnecessary ignore_for_file directive

lib/presentation/resource_manager/ReusableWidget/my_text_form_field.dart
Removed unnecessary comments related to late initializing and utilized null-aware operators for inputFormatters initialization in MyTextFormField class.
=> ✨ Remove unnecessary comments and use null-aware operators

lib/presentation/resource_manager/ReusableWidget/show_dialgue.dart, lib/presentation/views/home/home_screen.dart, linux/flutter/generated_plugin_registrant.cc, linux/flutter/generated_plugins.cmake, macos/Flutter/GeneratedPluginRegistrant.swift, pubspec.lock, pubspec.yaml, windows/flutter/generated_plugin_registrant.cc, windows/flutter/generated_plugins.cmake
Added a customized button to show an info dialog in the Home Screen, utilizing
the 'Awesome Dialog' package.
=> ✨ Add custom dialog to show info in Home Screen

lib/presentation/resource_manager/ReusableWidget/show_dialgue.dart, lib/presentation/views/home/home_screen.dart
Added new dialog types (error, success, and warning) to MyAwesomeDialogue
for displaying different types of dialogs in the application.
=> ✨ Add new dialog types to MyAwesomeDialogue

lib/presentation/views/home/home_screen.dart
Refactored dialogue instantiation in the HomeScreen widget for a cleaner and more
organized code structure.
=> ✨ Refactor: Update dialogue instantiation in HomeScreen widget

lib/presentation/views/home/home_screen.dart
- Update children layout in PageView for better alignment
- Refactor Row children in the body of the Scaffold
- Remove unnecessary import in the file
=> ✨ Improve layout in HomeScreen

lib/presentation/views/home/widgets/main_widget.dart
Simplified the build method in MainWidget by removing unnecessary
Expanded widget. Now the layout is more concise and easier to read.
=> ✨ Refactor: Simplify MainWidget build method

lib/presentation/resource_manager/styles_manager.dart
Add Playfair Display font styles for regular, medium, semi-bold, and bold in the styles manager file. This includes functions for each style with customizable font size and color.
=> ✨ Add Playfair Display Font Styles

lib/app/configurations/scroll_configurations.dart, lib/app/main_app.dart
Added a custom scroll behavior to MainApp using AppScrollBehavior to support
dragging on touch and mouse devices.
=> ✨ Add custom scroll behavior

lib/presentation/resource_manager/routes/app_go_router.dart, lib/presentation/resource_manager/routes/app_routes_names_and_paths.dart, lib/presentation/views/Login/login_screen.dart, lib/presentation/views/Login/widgets/login_form.dart, lib/presentation/views/base_screen.dart, lib/presentation/views/schools/school_screen.dart
- Added schools screen route and view to the app go router
- Updated app routes names and paths with schools screen details
- Imported necessary files for the schools screen
- Centered text in Schools Screen widget
- Imported go_router in login form widget
=> 🚀 Add schools screen route and view

lib/Data/Network/tools/app_error_handler.dart
Added new error status codes and messages for bad certificate, connection error,
and bad response handling. Also included these new status codes in the enum
DataSource and extended functionality in the ErrorHandler class.
=> ✨ Add new error status codes and messages

lib/presentation/views/certificates/certificates_screen.dart
Added CertificatesScreen widget to display a centered 'Certificates Screen' text in the app.
=> ✨ Add CertificatesScreen widget to display certificates

lib/presentation/views/cohort_settings/cohort_settings_screen.dart
Added new CohortSettingsScreen class to handle displaying cohort settings.
=> ✨ Add CohortSettingsScreen to project 🎨

lib/presentation/views/dashboard/dash_board_screen.dart
Added a new dashboard screen to display important information.
Focused on creating the initial structure of the screen.
=> ✨ Add dashboard screen to the application

lib/presentation/views/proctor/proctor_screen.dart
Add a new ProctorScreen view component for displaying the Proctor Screen
with a centered text widget.
=> ✨ Add proctor screen view component

lib/presentation/views/seating_numbers/seating_numbers_screen.dart
Add SeatingNumbersScreen component to display seating numbers.
This component extends BaseScreen for consistency.
=> ✨ Add SeatingNumbersScreen view component

lib/presentation/views/student/student_screen.dart
Added StudentScreen widget that extends BaseScreen for displaying student information on the screen.
=> ✨ Add StudentScreen and BaseScreen Widget

lib/presentation/views/subject_setting/subject_setting_screen.dart
Added a new screen to display subject setting information within the app.
=> ✨ Add Subject Setting Screen to project

lib/domain/controllers/auth_controller.dart
Replace print statements with debugPrint in AuthController for better
debugging practices.
=> ✨ Update debugPrint usage in AuthController

lib/presentation/resource_manager/routes/app_routes_names_and_paths.dart
Added new screens with their corresponding paths and names to the AppRoutesNamesAndPaths class. This will help in better organization and navigation within the application.
=> ✨ Add new paths and names in AppRoutesNamesAndPaths

lib/presentation/resource_manager/ReusableWidget/my_back_button.dart, pubspec.lock, pubspec.yaml
- Added a custom back button widget with conditional logic for web and
mobile platforms. 
- Updated dependencies for universal_html package version 2.2.4.
=> ✨ Add custom back button widget 🚪

lib/app/extensions/device_type_extension.dart
Added getters to check if the device type is mobile, tablet, or desktop.
=> ✨ Add device type getters

lib/presentation/views/base_screen.dart
- Refactored context usage in BaseScreen to simplify and improve readability.
- Updated references to AppResponsive class with context extension methods.
- Made changes to improve code maintainability and consistency.
=> ✨ Refactor: Update context usage in BaseScreen

lib/presentation/resource_manager/routes/app_go_router.dart
Updated route name for user screen and removed unused schools route for better
clarity and consistency in naming conventions.
=> ✨ Update route names in AppGoRouter

lib/presentation/resource_manager/routes/app_go_router.dart, lib/presentation/views/index.dart
Updated imports in app_go_router.dart to use a single import statement for views instead of individual imports.
=> 🔄 Refactor: Update imports in app_go_router.dart

lib/presentation/resource_manager/routes/app_go_router.dart, lib/presentation/views/admin_screen/admin_screen.dart, lib/presentation/views/admin_screen/widgets/add_new_user.dart, lib/presentation/views/index.dart
Added AdminScreen component along with the necessary form fields and dropdowns for adding a new user with admin privileges. Removed the UserScreen component as it is no longer used in the application.
=> ✨ Add admin screen and admin functionality

lib/app/main_app.dart, lib/domain/bindings/bindings.dart, lib/domain/services/side_menue_get_controller_service.dart, lib/presentation/views/base_screen.dart, lib/presentation/views/side_menue/side_menue.dart
Updated the side menu items to use the controller method for changing pages
instead of direct access.
=> ✨ Update side menu item taps to use controller

lib/domain/services/side_menue_get_controller_service.dart
Updated titles for Side Menu items:
- 'Class Rooms' instead of 'Classrooms'
- 'Set Degrees' instead of 'Scanning Grades'
- 'Control Mission' instead of 'Control Batch'
=> ✨ Refactor Side Menu Titles

lib/presentation/resource_manager/routes/app_go_router.dart, lib/presentation/resource_manager/routes/app_routes_names_and_paths.dart, lib/presentation/views/batch_documents/batch_documents_screen.dart, lib/presentation/views/index.dart
Added a new route and screen for Batch Documents Screen in the app. 
- Added BatchDocumentsScreen.dart with the required widget implementation.
- Defined path and name constants for Batch Documents Screen.
=> ✨ Add Batch Documents Screen

lib/domain/bindings/bindings.dart, lib/domain/services/side_menue_get_controller.dart, lib/presentation/views/base_screen.dart, lib/presentation/views/side_menue/side_menue.dart
- Renamed SideMenueGetControllerService to SideMenueGetController for clarity
and consistency in naming conventions.
=> ✨ Refactor(service): Rename SideMenueGetControllerService to SideMenueGetController

lib/domain/services/side_menue_get_controller.dart, lib/presentation/resource_manager/routes/app_go_router.dart, lib/presentation/resource_manager/routes/app_routes_names_and_paths.dart, lib/presentation/views/index.dart, lib/presentation/views/roles/roles_screen.dart
Added a new Roles screen to display roles information with corresponding routes. 
- Added Roles screen view and route
- Updated index.dart to export Roles screen
- Updated AppGoRouter to include Roles route
- Updated AppRoutesNamesAndPaths to define rolesScreen path and name
=> ✨ Add roles screen and routes

lib/domain/services/side_menue_get_controller.dart, lib/presentation/resource_manager/routes/app_go_router.dart
Add navigation listener in AppGoRouter to update the side menu controller
based on the current route name when navigating.
=> ✨ Add navigation listener in AppGoRouter

lib/presentation/resource_manager/ReusableWidget/my_text_form_field.dart
Refactored the MyTextFormField widget to improve layout and styling. 
Removed unnecessary Padding widget and updated TextFormField properties for better alignment and design.
=> ✨ Refactor: Update MyTextFormField layout and styling

lib/presentation/views/admin_screen/widgets/add_new_user.dart
Changed the hint text from "Select Role" to "Select Division" to accurately
reflect the purpose of the dropdown. Updated the variable names and logic
related to division selection for better clarity and functionality.
=> ✨ Update division selection in AddNewUserWidget

lib/Data/Models/User/login_response/login_response.dart, lib/Data/Models/User/login_response/login_response.g.dart, lib/domain/controllers/access_middle_ware.dart, pubspec.lock, pubspec.yaml
- Changed import statements to match updated file names.
- Renamed LoginResponse class and related files to follow lowercase naming convention.
- Updated UserProfile class with correct attribute names.
- Updated json_annotation to a direct main dependency.
Co-authored-by: [Your Name]
=> ✨ Refactor: Update file names and class names for consistency

lib/presentation/views/schools/school_screen.dart
The changes include using const keyword for Widgets in school_screen.dart.
=> ✨ Improve code readability and performance

lib/presentation/views/admin_screen/widgets/add_new_user.dart
- Updated label from 'Egyption ID' to 'Egyptian ID' for consistency
- Fixed button text alignment and styling for 'Add' and 'Back' buttons
=> ✨ Update form field labels and button styles

lib/presentation/resource_manager/routes/app_routes_names_and_paths.dart
- Updated route names to have consistent capitalization and spacing
- Renamed some route names for clarity and consistency with other names
=> ✨ Refactor route names in AppRoutesNamesAndPaths

lib/presentation/resource_manager/ReusableWidget/show_dialgue.dart
Adjusted title and description text styles in MyAwesomeDialogue class
and set the width to 50% of the screen width.
=> ✨ Update dialogue styles and width

lib/domain/services/side_menue_get_controller.dart
Updated the Sign Out button in the side menu to show an Awesome Dialogue confirming if the user wants to sign out before navigating to the login screen.
=> ✨ Add Awesome Dialogue to Sign Out Button

lib/domain/services/side_menue_get_controller.dart
Changed the tooltips for each menu item to better reflect their respective
functions. This improves user understanding and navigation.
=> ✨ Update tooltips for menu items

lib/domain/services/side_menue_get_controller.dart, lib/presentation/resource_manager/routes/app_go_router.dart, lib/presentation/resource_manager/routes/app_routes_names_and_paths.dart
Changed user screen path and name to admin screen path and name for
consistency and clarity in the app navigation.
=> ✨ Update admin screen routes and names

lib/presentation/resource_manager/styles_manager.dart
Added getters for various text styles in the styles manager to provide easy access to commonly used text styles.
=> ✨ Add getters for different text styles

lib/presentation/resource_manager/ReusableWidget/header_widget.dart
Added a new HeaderWidget component to display a header with custom text
and styling.
=> ✨ Add header widget component

lib/presentation/views/class_rooms/class_rooms_screen.dart
Imported and added HeaderWidget to display title in Class Rooms screen.
Updated layout with background color, padding, and Add Class Room button.
Ensuring consistent design and user experience across screens.
=> ✨ Add reusable header widget to Class Rooms Screen

lib/presentation/resource_manager/routes/app_go_router.dart, lib/presentation/views/class_rooms/widgets/render_seat.dart, lib/presentation/views/index.dart
Added a new route for rendering seat screen in the app with corresponding widget.
=> ✨ Add render seat screen route and widget

lib/presentation/views/class_rooms/class_rooms_screen.dart
Using the go_router package for improved navigation in the ClassRoomsScreen.
Introduced AppRoutesNamesAndPaths for route management.
=> 🔧 Refactor: Update navigation method in ClassRoomsScreen

lib/presentation/views/cohort_settings/cohort_settings_screen.dart
Incorporated a new layout design for the Cohort Settings Screen to improve
user experience and make it visually appealing.
=> ✨ Refactor Cohort Settings Screen layout

lib/presentation/resource_manager/ReusableWidget/add_dialogs.dart
- Capitalize MyDialogs class name for consistency and clean up syntax for better readability.
=> ✨ Refactor: Update capitalization in MyDialogs class and clean up syntax

lib/presentation/views/cohort_settings/cohort_settings_screen.dart
Added a dialog for users to input a new cohort name and create a new cohort
based on the input.
=> ✨ Add dialog for adding new cohort

lib/presentation/views/dashboard/widgets/calendar_widget.dart, pubspec.lock, pubspec.yaml
Added table_calendar dependency to utilize a calendar widget in the dashboard view.
Also added intl dependency to support internationalization functionalities.
=> ✨ Add table_calendar and intl dependencies

lib/presentation/views/dashboard/widgets/notification_card_widget.dart
Added a new NotificationCardWidget to display notifications in the dashboard.
The widget shows the school name and a brief message.
Includes styling and responsive design for different screen widths.
=> ✨ Add Notification Card Widget

lib/presentation/views/dashboard/widgets/recruitment_widget.dart
Added a new widget for displaying recruitment data with styling and layout enhancements.
=> ✨ Add recruitment data widget

lib/presentation/views/dashboard/widgets/recruitment_widget.dart
Simplify the structure of the recruitment data widget by removing GetBuilder
dependency and optimizing the layout rendering for better performance.
=> ✨ Refactor recruitment data widget layout

lib/presentation/views/dashboard/widgets/profile_card_widget.dart
- Added a new ProfileCardWidget class to display user profile information.
- Includes profile picture, username, role, and joined date.
- Styled with a container, shadow, and border radius for a sleek look.
=> ✨ Add profile card widget

lib/presentation/views/dashboard/widgets/clock_pointer.dart
Added the logic to draw clock hands on the canvas with minute, hour, and second
calculations. Used custom painter to achieve this functionality.
=> ✨ Add clock pointer functionality

lib/presentation/views/dashboard/widgets/clock_widget.dart
Added a new ClockWidget class to display a clock on the dashboard.
The clock includes shadows, padding, and a circular design.
The clock is not yet functional but will be in a future update.
=> ✨ Add clock widget to dashboard

lib/presentation/views/dashboard/widgets/index.dart
Added exports for new dashboard widgets to improve modularity and organization.
=> ✨ Add dashboard widgets exports

lib/presentation/resource_manager/routes/app_go_router.dart, lib/presentation/views/dashboard/dash_board_screen.dart
- Rename DashBoardScreen to DashboardScreen
- Update imports and references accordingly.
=> ✨ Refactor: Update dashboard screen naming convention

lib/presentation/views/dashboard/widgets/clock_widget.dart
Refactor ClockWidget layout to use a Column instead of GetBuilder for better
optimization and organization. Remove unnecessary code and comments to improve
readability and maintainability.
=> ✨ Adjust ClockWidget layout in Dashboard view

lib/presentation/resource_manager/ReusableWidget/customized_button.dart, lib/presentation/resource_manager/ReusableWidget/my_text_form_field.dart, lib/presentation/resource_manager/ReusableWidget/show_dialgue.dart, lib/presentation/resource_manager/theme_manager.dart, lib/presentation/views/Login/widgets/select_school_form.dart, lib/presentation/views/admin_screen/widgets/add_new_user.dart, lib/presentation/views/cohort_settings/cohort_settings_screen.dart, lib/presentation/views/side_menue/side_menue.dart
Changed "nunitoRegulerStyle" to "nunitoRegularStyle" in multiple files to correct spelling errors and maintain consistency in font style naming conventions.
=> ✨ Fix: Corrected spelling errors in font style names

lib/presentation/views/set_degrees/set_degrees_screen.dart
Added a header widget with "Student Grades" text and a text field for input in the SetDegreesScreen view.
=> ✨ Add header widget and text field in SetDegreesScreen

lib/presentation/views/set_degrees/widgets/bar_code_subjects_widget.dart
Added BarCodeSubjects Widget to display student name, grade, and class information
on a barcode scanning screen. This widget will improve user experience and provide
relevant information at a glance.
=> ✨ Add BarCodeSubjects Widget to display student information

lib/presentation/views/seating_numbers/seating_numbers_screen.dart
Update import path for seating_number_tab_view_controller in seating_numbers_screen.
=> ✨ Refactor import path for seating_number_tab_view_controller 🛠

lib/domain/bindings/bindings.dart, lib/domain/controllers/dashboard_controller.dart, lib/domain/indices/dash_board_index.dart
Added DashBoardBindings to lazy load the DashboardController in order to improve performance and optimize resource usage.
=> ✨ Add DashboardBindings to lazy load DashboardController

lib/domain/controllers/dashboard_controller.dart, lib/presentation/views/dashboard/widgets/clock_widget.dart
Refactor clock widget to use GetBuilder for dynamic updates and clean up
unnecessary code. Update dashboard controller to handle time updates and
period detection efficiently.
=> ✨ Refactor clock widget and dashboard controller

lib/presentation/views/subject_setting/subject_setting_screen.dart
- Refactored the layout of the subject setting screen to use a Container
with specified color and padding
- Added functionality to add a new subject with a dialog that prompts
the user to enter a subject title and name
=> ✨ Refactor subject setting screen layout and add functionality to add new subject

lib/presentation/resource_manager/ReusableWidget/elevated_back_button.dart
Import necessary packages and create a new widget ElevatedBackButton with
custom styling and functionality to navigate back.
=> ✨ Add ElevatedBackButton widget

lib/presentation/views/admin_screen/admin_screen.dart, lib/presentation/views/admin_screen/widgets/add_new_user.dart, lib/presentation/views/cohort_settings/cohort_settings_screen.dart
- Refactored the design of the AddNewUserWidget in the admin screen
- Updated the colors and borders for a more appealing look
- Replaced Back button with custom ElevatedBackButton component
=> ✨ Refactor: Improve UI design for AddNewUserWidget

lib/presentation/views/subject_setting/subject_setting_screen.dart
Replaced on tap function with ElevatedBackButton widget to simplify and improve
readability of the code. Also removed unused imports and comments.
=> ✨ Add elevated back button in subject setting screen

lib/presentation/views/admin_screen/admin_screen.dart
- Add 'MyDialogs.showAddDialog' function for displaying add dialog
- Replace Get.defaultDialog with 'MyDialogs.showAddDialog' to improve reusability
=> ✨ Add reusable dialog function for adding new user

lib/presentation/views/admin_screen/widgets/add_new_user.dart
Added styling to the "Add new Cohort" title in the AddNewUserWidget component
to improve visibility and user experience.
=> ✨ Add new user cohort title styling

lib/presentation/views/student/student_screen.dart, pubspec.lock, pubspec.yaml
Update StudentScreen to include Font Awesome icons for desktop actions.
Integrate Font Awesome Flutter package v10.7.0 for icon support.
=> ✨ Add font awesome icons to StudentScreen

lib/presentation/views/student/student_screen.dart, lib/presentation/views/student/widgets/header_student_widget.dart
Added a separate header widget for the student screen to improve code
organization and maintainability. Removed unnecessary icons and tooltips
from the student screen widget to simplify the UI.
=> ✨ Refactor the student screen header widget

lib/presentation/views/student/widgets/add_new_student.dart
- Updated the UI of the AddNewStudent widget to include new input fields
and adjust the layout for better user experience.
=> ✨ Refactor: Update AddNewStudent widget UI

lib/presentation/views/student/widgets/add_single_student.dart
changed AddNewStudent To AddSingleStudent widget for better naming conventions
=> ✨ refactor:changed AddNewStudent To AddSingleStudent widget

lib/presentation/views/student/widgets/header_student_widget.dart
Added a new title 'Students' to the header widget with specific styling.
=> ✨ Add 'Students' title to HeaderWidget

lib/presentation/views/certificates/certificates_screen.dart
- Updated the layout of CertificatesScreen to use an Expanded widget with a
Container for better styling and padding. This change also includes importing
the ColorManager for background color consistency.
=> ✨ refactor(certificates): Update CertificatesScreen layout

lib/presentation/views/certificates/certificates_screen.dart
Simplified the body widget in CertificatesScreen for better readability and
maintenance. Removed unnecessary Expanded widget.
=> ✨ Refactor certificates_screen layout 🎨

lib/presentation/views/proctor/proctor_screen.dart
Added UI elements for creating new proctor and selecting mission year in the Proctor Screen. This makes it easier for users to interact with the application.
=> ✨ Add UI elements for creating new proctor and selecting mission year

lib/presentation/views/proctor/proctor_screen.dart, lib/presentation/views/proctor/widgets/add_new_proctor.dart
Changed the layout of the AddNewProctor widget form to include
proper padding and styling for text input fields. Removed unused
code and added appropriate decorations for text form fields.
=> ✨  Update AddNewProctor widget form styling

lib/presentation/views/proctor/widgets/assign_proctor_to_exam_by_room_id.dart
Added a new widget called AssignProctorToExamByRoomId for assigning
exams to proctors based on room ID. This widget includes UI elements for
viewing morning and night exams, selecting a proctor, and assigning the
exam to the proctor.
=> ✨ Add new widget AssignProctorToExamByRoomId

lib/presentation/views/proctor/widgets/un_assign_proctor_from_room.dart
Added a new widget UnAssignProctorFromRoom for unassigning proctors from exam rooms. This widget includes UI elements for selecting and unassigning proctors from exam rooms.
=> ✨ Add UnAssignProctorFromRoom widget

lib/presentation/resource_manager/ReusableWidget/drop_down_button.dart
Added a new searchEnabled property to the MultiSelectDropDownView
class, allowing for the option to enable/disable search functionality
in the dropdown. The value of searchEnabled is now dynamically set
based on the searchEnabled property passed to the constructor.
=> ✨ Add searchEnabled property to MultiSelectDropDownView 🔄

lib/presentation/views/control_mission/widgets/header_mission_widget.dart
Import extension and resources for header mission widget.
Create HeaderMissionWidget class with desktop and mobile layouts.
Implement navigation icons for mobile view.
Ensure easy access to create a new mission with an add icon.
=> ✨ Add header mission widget with navigation icons

lib/presentation/views/control_mission/widgets/create_mission_widget.dart
Adding the CreateMissionWidget class to handle creating new missions in the control mission section. This widget includes a form for inputting the mission name and selecting education years.
=> ✨ Add CreateMissionWidget in control mission section

lib/presentation/views/control_mission/widgets/control_mission_quick_review_widget.dart
Added a new widget ControlMissionQuickReviewWidget with necessary styling
and interactions for quick review of missions. This widget includes
containers, text styling, and tap interactions for Distribution and
ReviewMission actions.
=> ✨ add ControlMissionQuickReviewWidget 🚀

lib/presentation/views/control_mission/widgets/review_mission_header_widget.dart
Added ReviewMissionHeaderWidget to display the header for reviewing a mission.
=> ✨ Add ReviewMissionHeaderWidget

lib/presentation/views/control_mission/widgets/review_mission_header_widget.dart
Refactor ReviewMissionHeaderWidgetWidget to use custom font style nunitoBold
to improve text visibility and enhance design consistency.
=> ✨ Update style in ReviewMissionHeaderWidgetWidget

lib/presentation/views/control_mission/widgets/review_widget.dart
Added dropdown menus for grade and subject selection in the ReviewWidget class
to allow users to choose the grade and subject for a mission review.
=> ✨ Add dropdown menus for grade and subject selection

lib/presentation/resource_manager/routes/app_go_router.dart, lib/presentation/resource_manager/routes/app_routes_names_and_paths.dart, lib/presentation/views/distribution/distribution_screen.dart
=> ✨ Add distribution screen route and screen

lib/presentation/resource_manager/routes/app_go_router.dart, lib/presentation/views/class_rooms/widgets/exam_room.dart
- Renamed ExamRoom Widget to ExamRoomScreen for clarity and consistency.
- Updated references to ExamRoom Widget across the app to ExamRoomScreen.
=> ✨ Refactor Exam Room Widget

lib/presentation/views/class_room_seats/widgets/render_seat_widget.dart
Added RenderSeats widget component to render seat numbers and students' names on seats in the classroom.
=> ✨ Add render seats widget component

lib/presentation/views/class_room_seats/class_room_seats_screen.dart
- Added ClassRoomSeatsScreen component for adding new classes to the system
- Includes form fields for class name, building name, floor name, and max capacity
=> ✨ Add ClassRoomSeatsScreen component

lib/presentation/views/control_mission/widgets/delete_mission.dart
Added a new widget for displaying a dialog box to confirm deleting a mission.
The dialog provides options to either confirm or cancel the deletion.
=> ✨ Add Delete Mission Dialog Widget

lib/presentation/views/control_mission/widgets/delete_mission_widget.dart
Extracted DeleteMissionDialog into DeleteMissionWidget to improve code
readability and maintainability. This change simplifies the structure of
the widget and makes it more reusable.
=> ✨ Refactor DeleteMissionDialog into DeleteMissionWidget

lib/presentation/views/control_mission/widgets/add_exam_room_widget.dart
Adds a new widget AddExamRoomWidget for adding a new exam room. This widget
contains form elements for selecting class room, class type, and adding a new
room name. Also, includes a button to go back.
=> ✨ Add AddExamRoomWidget component

lib/presentation/views/control_mission/widgets/header_mission_widget.dart, lib/presentation/views/dashboard/widgets/clock_widget.dart
Added mission control title to the header widget in the control mission view
for better visibility and UI consistency.
=> ✨ Add mission control title 🚀

lib/Data/Network/response_handler.dart, lib/Data/handlers/implementation/login_response_implemantation_handler.dart, lib/Data/handlers/interfaces/response_interface.dart
Added a mixin and implementation handler for the response interface, along with
updating the response handler to handle login responses efficiently.
=> ✨ Add response interface mixin and login response handler

lib/domain/controllers/auth_controller.dart
Implement new response handling logic in login process in AuthController to improve error handling and token storage.
=> 🔧 Refactor login response handling in AuthController. 

lib/domain/controllers/auth_controller.dart
Removed unnecessary debugPrint statement to improve code readability.
=> ✨ Remove debugPrint statement in AuthController 🐛

lib/Data/Models/base_model.dart, lib/Data/Models/user/login_response/login_response.dart, lib/Data/Models/user/login_response/user_profile.dart
Imported base model to user login response and user profile to allow for code reusability.
=> ✨ Add base model to user login response

lib/Data/Models/user/login_response/login_response.dart, lib/Data/handlers/implementation/login_response_implemantation_handler.dart, lib/domain/controllers/access_middle_ware.dart, lib/domain/controllers/auth_controller.dart
Refactor LoginResponse references to LoginResponseModel for consistency
across the auth flow controllers and handlers. Update type definitions in
controllers and handlers to match the new model naming convention.
=> ✨ Refactor: Update LoginResponse to LoginResponseModel in auth flow

lib/Data/Models/school/school_response/school_response.dart, lib/Data/Models/user/login_response/login_response.dart
Improve readability and maintainability by properly formatting the model
constructors in SchoolResponseModel and LoginResponseModel classes.
=> ✨ Refactor model constructors for SchoolResponseModel and LoginResponseModel

lib/Data/Models/student/student_model.dart
Added a new StudentModel class with properties for grades ID, schools ID,
cohort ID, school class ID, first name, second name, third name, and created by
ID. Includes constructors for instantiation and JSON serialization.
=> ✨ Add student model with properties

lib/Data/Models/class_desk/class_desk_model.dart
Added ClassDeskModel class to handle the attributes schoolClassID,
columnNum, and rowNum. This class includes methods to serialize and
deserialize the object to and from JSON format.
=> ✨ Add ClassDeskModel with schoolClassID, columnNum, and rowNum

lib/Data/Models/school_classes/school_classes_model.dart
Added the SchoolClassesModel class with basic attributes such as name, maxCapacity,
floor, rows, columns, and schoolsID. Includes toJson and fromJson methods for
serialization/deserialization.
=> ✨ Add SchoolClassesModel with basic attributes

lib/Data/Models/school/school_type/school_type_model.dart
Added SchoolTypeModel class to represent the type of school. Includes properties for name, constructor, fromJson, and toJson methods.
=> ✨ Add SchoolTypeModel class

lib/Data/Models/control_mission/control_mession_model.dart
Added the ControlMessionModel class that extends BaseModel, includes properties
educationYearID, schoolsID, and name, toJson and fromJson methods.
=> ✨ Add Control Mission Model class

lib/Data/Models/exam_room/exam_room_model.dart
Added ExamRoomModel class to manage exam room data in the application. The class
has attributes for controlMissionID, schoolClassID, name, stage, and capacity.
Included methods for JSON serialization and deserialization.
=> ✨ Add ExamRoomModel class

lib/Data/Models/school/grade_response/grade_res_model.dart, lib/Data/Models/school/grade_response/grades_res_model.dart
Refactored the GradesResModel and GradeResModel classes to include proper
attributes and methods for handling grade response data. This involved
updating the attributes, constructor, and methods to ensure accurate data
parsing and serialization.
=> ✨ Refactor: Update GradesResModel and GradeResModel classes

lib/Data/Models/base_model.dart, lib/Data/Models/class_desk/class_desk_model.dart, lib/Data/Models/control_mission/control_mession_model.dart, lib/Data/Models/education_year/education_year_model.dart, lib/Data/Models/exam_mession/exam_mession_model.dart, lib/Data/Models/exam_room/exam_room_model.dart, lib/Data/Models/school/grade_response/grade_res_model.dart, lib/Data/Models/school/school_classes/school_classes_model.dart, lib/Data/Models/student/student_model.dart, lib/Data/Models/user/login_response/login_response.dart, lib/Data/Models/user/login_response/user_profile.dart
Removed inheritance from BaseModel in multiple model classes to simplify the
class structure and improve code readability. This change streamlines the
models and eliminates unnecessary dependencies.
=> ✨ Refactor: Remove inheritance in model classes

lib/Data/Network/tools/dio_factory.dart
Refactor DioFactory to cache Dio instance for better performance.
=> ✨ Add Dio instance caching

lib/Data/Network/tools/dio_factory.dart
Updated DioFactory to use a static instance variable _dioInstance instead of non-static _instance for improved consistency and performance.
=> ✨ Refactor: Update DioFactory to use static instance variable

lib/Data/Models/user/login_response/user_profile_model.dart, lib/Data/Models/user/users_res/users_res_model.dart
Added password field and audit fields (createdBy, createdAt, updatedBy,
updatedAt, and active) to the user profile model in order to store and manage
user data securely.
=> ✨ Add password and audit fields to user profile model

lib/domain/controllers/auth_controller.dart
- Refactor login handling to use Either type for response
- Show error dialogue if login fails
- Save token and profile data on successful login
=> ✨ Refactor login handling in AuthController

lib/Data/Network/response_handler.dart
Updated the network response handler to include the option to pass a request body
in addition to the request parameters for different request types.
=> ✨ Add support for passing request body in network requests

lib/domain/controllers/auth_controller.dart
- Updated token refreshing logic in `AuthController.dart` to use Dio for API calls
- Added functionality to handle token refreshing and updating in local storage and profile controller
=> ✨ Refactor authentication controller for token refreshing

lib/Data/Network/response_handler.dart
- Only return Right if response data status is true
- Return Left with failure details if status is false
=> ✨ Improve error handling in ResponseHandler

lib/presentation/resource_manager/ReusableWidget/elevated_add_button.dart
Added a new reusable ElevatedAddButton widget to be used in the presentation layer for adding items.
=> ✨ Add reusable ElevatedAddButton widget

lib/Data/Models/subject/subject_res_model.dart, lib/Data/Models/subject/subjects_res_model.dart, lib/Data/Network/tools/dio_factory.dart, lib/app/configurations/app_links.dart, lib/domain/bindings/bindings.dart, lib/domain/controllers/subject_controller.dart, lib/domain/indices/subjects_index.dart, lib/presentation/resource_manager/routes/app_go_router.dart, lib/presentation/views/subject_setting/subject_setting_screen.dart
Add an elevated add button to the Subject Setting Screen for easy access to
adding new subjects. This makes the UI more intuitive and user-friendly.
=> ✨ Add elevated add button to Subject Setting Screen

lib/Data/Models/school/grade_response/grades_res_model.dart
Refactored the `fromJson` method in the `GradesResModel` class to simplify
the logic and improve readability by using `List.from` instead of manual
iteration.
=> ✨ Refactor grade response model constructor

lib/Data/Models/cohort/cohort_res_model.dart, lib/Data/Models/cohort/cohorts_res_model.dart
Created new models CohortResModel and CohortsResModel to handle cohort data and
their list. These models will be used to serialize and deserialize cohort data
in the app.
=> ✨ Add new models CohortResModel and CohortsResModel

lib/domain/bindings/bindings.dart, lib/domain/controllers/cohorts_settings.dart, lib/domain/indices/cohort_index.dart, lib/domain/indices/index.dart, lib/presentation/resource_manager/routes/app_go_router.dart
Added CohortSettingsBindings to handle dependencies for CohortSettingsScreen.
Exported subjects_index in indices/index.dart and cohorts_settings in cohort_index.dart.
=> ✨ Add CohortSettingsBindings dependencies

lib/domain/controllers/cohorts_settings.dart, lib/domain/controllers/cohorts_settings_controller.dart, lib/domain/indices/cohort_index.dart
Updated the filename of the cohorts settings controller from cohorts_settings.dart
to cohorts_settings_controller.dart for clarity and consistency.
=> ✨ Refactor: Update cohorts settings controller filename

lib/Data/Models/cohort/cohort_res_model.dart, lib/Data/Models/cohort/cohorts_res_model.dart, lib/domain/bindings/bindings.dart, lib/domain/controllers/cohorts_settings_controller.dart, lib/presentation/views/cohort_settings/cohort_settings_screen.dart
- Update data mapping in CohortsResModel.fromJson
- Update types in CohortResModel
- Update CohortsSettingsController to fetch and add cohorts
=> ✨ Refactor: Update CohortsResModel and CohortResModel

lib/domain/controllers/cohorts_settings_controller.dart, lib/presentation/views/cohort_settings/cohort_settings_screen.dart
Added MyAwesomeDialogue for deletion confirmation in the CohortSettingsScreen.
When deleting a cohort, a confirmation dialogue is shown to ensure the user
wants to proceed with the deletion. If confirmed, the cohort is deleted and a
success/error message is displayed accordingly.
=> ✨ Add MyAwesomeDialogue for deletion confirmation

lib/domain/controllers/cohorts_settings_controller.dart, lib/presentation/views/cohort_settings/cohort_settings_screen.dart, lib/presentation/views/cohort_settings/widgets/add_cohort_widget.dart
Add a loading indicator when fetching all cohorts in the cohort settings screen.
=> ✨ Add loading indicator when fetching all cohorts

lib/domain/controllers/subject_controller.dart, lib/presentation/views/subject_setting/subject_setting_screen.dart
- Refactored the layout in SubjectSettingScreen to use Expanded widget for better UI design.
- Updated loading logic for subjects to display CircularProgressIndicator when loading.
- Removed unnecessary getAllSubjects() call in SubjectsController.
=> ✨ Refactor subject setting screen layout and loading logic

lib/domain/controllers/subject_controller.dart, lib/presentation/views/cohort_settings/cohort_settings_screen.dart, lib/presentation/views/subject_setting/subject_setting_screen.dart
Simplified the cohort deletion process by refactoring the code for better
readability and maintainability. Removed nested ternary conditions and
extracted the confirmation dialogue into a separate method for improved
code structure.
=> ✨ Refactor cohort deletion logic

lib/domain/controllers/cohorts_settings_controller.dart, lib/domain/controllers/subject_controller.dart
Removed deleteLoading state and unnecessary update calls in both SubjectsController and CohortSettingsController to simplify the code and improve performance.
=> ✨ Remove deleteLoading state in controllers

lib/app/main_app.dart, lib/domain/bindings/bindings.dart, lib/domain/controllers/index.dart, lib/domain/indices/auth_index.dart, lib/domain/indices/cohort_index.dart, lib/domain/indices/dash_board_index.dart, lib/domain/indices/home_index.dart, lib/domain/indices/index.dart, lib/domain/indices/subjects_index.dart, lib/main.dart, lib/presentation/resource_manager/routes/app_go_router.dart, lib/presentation/views/Login/widgets/login_form.dart
Added new imports and bindings to improve the structure of the app.
Updated main app file to include domain bindings for class room controller.
=> feat: Update imports and bindings in main app

lib/presentation/resource_manager/ReusableWidget/my_text_form_field.dart, lib/presentation/resource_manager/color_manager.dart, lib/presentation/resource_manager/theme_manager.dart, lib/presentation/views/Login/widgets/login_form.dart, lib/presentation/views/class_room_seats/class_room_seats_screen.dart
- Refactored the text form fields in the login and class room seats screens to use a custom reusable widget, `MytextFormFiled`, which allows for easier customization of the text field's border colors and other properties.
- Updated the `ColorManager` class to use `const` for the primary and grey colors for better performance and consistency.
- Made minor font size and style adjustments to the `MytextFormFiled` widget.
=> Refactor text form fields and color management

lib/domain/bindings/bindings.dart, lib/domain/controllers/index.dart, lib/presentation/resource_manager/routes/app_go_router.dart, lib/presentation/resource_manager/routes/app_routes_names_and_paths.dart, lib/presentation/views/class_room_seats/class_room_seats_screen.dart, lib/presentation/views/class_rooms/class_rooms_screen.dart
- Added conditional rendering for different scenarios when fetching class rooms.
- Updated styling to ensure consistent design for class room cards.
- Tweaked padding and alignment for better visual appeal.
=> feat(presentation): Refactor ClassRoomsScreen UI to improve readability

lib/presentation/views/class_room_seats/class_room_seats_screen.dart
Refactored the logic for generating class seats based on the number of rows
in the class. Used List.generate instead of List.filled for better performance.
=> feat: optimize class room seats screen logic

lib/Data/Models/class_room/class_room_res_model.dart
in ClassRoomResModel
- updatedBy changed from Null to int
- updatedAt changed from Null to DateTime
=> ✨ Update: Update null fields to proper types

lib/Data/Models/student_seat/student_seat_model.dart, lib/domain/controllers/class_room_controller.dart, lib/presentation/views/class_room_seats/class_room_seats_screen.dart, lib/presentation/views/class_room_seats/widgets/render_seat_widget.dart
- Refactored the RenderSeats widget to improve readability and performance.
- Updated import statements for better organization and clarity.
=> ✨ Refactor render seat widget

lib/presentation/views/Login/widgets/login_form.dart
Simplified login form layout structure with improved readability and added
keyboard listener for submitting the form with the enter key.
=> ✨ Refactor: updated login form layout and added keyboard listener

lib/presentation/views/Login/widgets/login_form.dart
Refactor login logic in the login form widget to make it simpler and easier to
understand. Created a separate function "_login" to handle the login process.
Now the "onPressed" event triggers this function instead of containing the
entire login process. This improves code readability and maintainability.
=> ✨ Simplify login logic

lib/domain/controllers/class_room_controller.dart, lib/presentation/resource_manager/ReusableWidget/app_dialogs.dart, lib/presentation/resource_manager/ReusableWidget/elevated_edit_button.dart, lib/presentation/resource_manager/ReusableWidget/my_text_form_field.dart, lib/presentation/views/admin_screen/admin_screen.dart, lib/presentation/views/batch_documents/widgets/cover_sheet_screen.dart, lib/presentation/views/class_room_seats/class_room_seats_screen.dart, lib/presentation/views/class_rooms/class_rooms_screen.dart, lib/presentation/views/class_rooms/widgets/edit_class_room_widget.dart, lib/presentation/views/cohort_settings/cohort_settings_screen.dart, lib/presentation/views/proctor/proctor_screen.dart, lib/presentation/views/schools/Widgets/grade_system_widget.dart, lib/presentation/views/schools/school_screen.dart, lib/presentation/views/subject_setting/subject_setting_screen.dart, pubspec.lock
🔧 Fix MytextFormFiled isNumber property in My_text_form_field
=> ✨ Add editClassRoom method in ClassRoomController

lib/presentation/views/class_rooms/widgets/edit_class_room_widget.dart
Refactor the Form widget to add validation logic and check for required fields
when editing a class room in the EditClassRoomWidget component. This change
ensures better user experience by guiding users to provide necessary information.
=> ✨ Improve form validation on EditClassRoomWidget

lib/presentation/views/class_room_seats/class_room_seats_screen.dart
Added form validation to the class name field in the Add New Class form to ensure that a class name is required before submitting the form.
=> ✨ Add form validation to class name field

lib/Data/Network/response_handler.dart, lib/Data/Network/tools/dio_factory.dart, lib/domain/controllers/auth_controller.dart, lib/domain/services/token_service.dart, lib/presentation/resource_manager/routes/app_go_router.dart
components for better token handling.
=> 🔨 Refactor auth controller refresh token method and ResponseHandler

lib/Data/Network/response_handler.dart, lib/domain/controllers/auth_controller.dart
In auth_controller.dart:
- Changed the error handling in the refresh token function to use onError
callback instead of try-catch block for better error management.
- Improved the handling of errors by using a custom ErrorHandler class.
- Updated the logic for refreshing tokens and handling response data.
In response_handler.dart:
- Modified the token expiration check time from 55 to 15 seconds for better
token refresh timing accuracy.
These changes aim to enhance the reliability and efficiency of token handling
in the authentication process.
=> 🔧 Refactor: Improve error handling in refresh token function

lib/presentation/views/batch_documents/batch_documents_screen.dart, lib/presentation/views/class_room_seats/class_room_seats_screen.dart
to use WidgetStateProperty instead of MaterialStateProperty.
=> ✨ Fix: Updated overlayColor property in BatchDocumentsScreen

lib/presentation/views/cohort_settings/widgets/add_cohort_widget.dart
Simplified the add cohort logic in AddCohortWidget to improve readability and user experience.
=> ✨ Refactor add cohort functionality

lib/presentation/views/cohort_settings/cohort_settings_screen.dart
- Refactor the cohort settings screen to improve readability and maintainability
- Updated the way cohort information is displayed and handled in the screen
- Implemented a searchable list view for better user experience
=> ✨ Refactor cohort settings screen

lib/Data/Models/education_year/education_year_model.dart, lib/Data/Models/education_year/educations_years_res_model.dart, lib/app/configurations/app_links.dart, lib/domain/bindings/bindings.dart, lib/domain/controllers/SeatingNumbersControllers/CreateCoversSheetsController.dart, lib/domain/controllers/school_controller.dart, lib/presentation/views/batch_documents/batch_documents_screen.dart, lib/presentation/views/batch_documents/widgets/add_new_cover_widget.dart, lib/presentation/views/class_room_seats/class_room_seats_screen.dart, lib/presentation/views/schools/Widgets/add_new_school.dart, pubspec.lock
- Updated the development server URL in the AppLinks class
- Removed an unnecessary line of code in the SchoolController class
- Changed the label font style in the BatchDocumentsScreen class
- Added a showChipSelect property in the AddNewCoverWidget class
- Changed the font style of the "Add" button in the AddNewCoverWidget class
- Removed unused imports and commented out code in the ClassRoomSeatsScreen class
- Fixed a bug in the ClassRoomSeatsScreen class where the count variable was not being reset
=> Cover-sheet

lib/presentation/views/cohort_settings/cohort_settings_screen.dart
Added a new empty state widget to display "No data found" message when
there is no data available in the list. This improves user experience.
=> ✨ Add empty state widget when no data found

lib/presentation/views/cohort_settings/cohort_settings_screen.dart
Simplify the onTap method in CohortSettingsScreen for better readability and
maintainability. Remove unnecessary commented-out code and refactor to
initialize SubjectsController directly.
=> ✨ Refactor CohortSettingsScreen onTap method

lib/presentation/views/cohort_settings/cohort_settings_screen.dart
- Remove unnecessary SubjectsController instantiation
- Refactor dialog content for subject selection
- Improve search field styling and functionality
=> ✨ Update subject selection in cohort settings

lib/presentation/resource_manager/ReusableWidget/drop_down_button.dart
Refactor the MultiSelectDropDownView component in drop_down_button.dart by:
- Removing unnecessary ternary operation for showChipInSingleSelectMode
- Updating constructor formatting for improved readability
- Adding logic to conditionally render selectedItemBuilder based on showChipSelect
This commit enhances the code structure and removes redundant code.
=> ✨ Refactor MultiSelectDropDownView component

lib/app/configurations/app_links.dart, lib/domain/controllers/cohorts_settings_controller.dart, lib/presentation/views/cohort_settings/cohort_settings_screen.dart
- Rename index variable in list item builder for clarity
- Update decoration properties for better readability
- Modify syntax for bottom navigation bar definition
- Fix syntax error in itemBuilder function for subject selection
- Add search functionality to subject selection dropdown
=> ✨ Refactor cohort settings screen UI components

lib/app/configurations/app_links.dart, lib/domain/controllers/cohorts_settings_controller.dart, lib/presentation/views/cohort_settings/cohort_settings_screen.dart
Refactored the CohortSettingsScreen to allow deleting subjects from a cohort by adding a deleteSubjectFromCohort method in the CohortsSettingsController. Updated the UI to reflect this change for a better user experience.
=> ✨ feat: Delete subject from cohort

lib/domain/controllers/auth_controller.dart, lib/domain/services/side_menue_get_controller.dart, lib/domain/services/token_service.dart
Refactor sign out logic in SideMenueGetController to handle sign out process
asynchronously and clean up token data before navigating to login screen.
=> ⚡️ Refactor sign out logic in SideMenueGetController

lib/domain/controllers/school_controller.dart, lib/presentation/views/Login/widgets/select_school_form.dart
🔒 Save and delete school information using Hive in SchoolController.
=> ✨ Add :sparkles: saveToSchoolBox and deleteFromSchoolBox methods in SchoolController

lib/domain/bindings/bindings.dart, lib/domain/controllers/auth_controller.dart, lib/domain/controllers/profile_controller.dart
- Refactored signOut method in AuthController to use Future.wait for
better code organization and efficiency
- Added deleteProfileFromHiveBox method in ProfileController
- Included AuthController as lazy dependency in SideMenuBindings
=> ✨ Refactor: Update signOut functionality 🚪

lib/presentation/views/class_room_seats/class_room_seats_screen.dart, lib/presentation/views/class_room_seats/widgets/render_seat_widget.dart, lib/presentation/views/class_rooms/widgets/edit_class_room_widget.dart
- Update classNumber controller in class room seats screen
- Update classSeats state in edit class room widget.
=> 🔧 Update class room seats screen and edit class room widget

lib/domain/bindings/bindings.dart, lib/domain/controllers/class_room_controller.dart, lib/presentation/views/class_rooms/class_rooms_screen.dart
- Update the layout in ClassRoomsScreen
- Modify ClassRoomController methods for adding rooms
- Use Hive to get the Schools_ID from the 'School' box
=> ✨ feat: Refactor class rooms screen and controller

lib/domain/controllers/studentsController/addNewStudentController.dart, lib/domain/controllers/studentsController/student_controller.dart, lib/presentation/views/student/widgets/add_single_student_widget.dart, lib/presentation/views/student/widgets/edit_student_widget.dart, lib/presentation/views/student/widgets/header_student_widget.dart
Change the text color of the title in Add Single Student Widget to primary color.
=> ✨ Update Add Single Student Widget title color

lib/app/extensions/pluto_row_extension.dart, lib/domain/controllers/studentsController/student_controller.dart
Ensure students are loaded before converting to rows for display in the UI.
=> ✨ Add cascade loading for student data conversion

lib/domain/controllers/class_room_controller.dart, lib/domain/controllers/cohorts_settings_controller.dart, lib/domain/controllers/subject_controller.dart
- Update "Created_By" value in "CohortsSettingsController" and "SubjectController"
- Update "School_Type_ID" value in "CohortsSettingsController"
- Import Hive Flutter in relevant controllers
=> ⚙️ Refactor: Update "Created_By" and "School_Type_ID" values to use data from Hive

lib/presentation/resource_manager/ReusableWidget/app_dialogs.dart
Add GetX Dialog method for displaying a dialog using GetX library in Flutter.
=> ✨ Add GetX Dialog functionality 🚀

lib/presentation/resource_manager/validations.dart
The commit adds a new function `multiSelectDropDownRequiredValidator` to handle
validations for a multi-select dropdown field to ensure it is not null or empty.
=> ✨ Add multiSelectDropDownRequiredValidator validation function

lib/presentation/views/student/widgets/add_single_student_widget.dart
🛠 Refactor: Reformat code for AddNewStudentWidget
=> ✨ Add: Import model for value item

lib/domain/controllers/studentsController/add_new_student_controller.dart
ℹ️ This commit adds the functionality to update the student list after a new student has been added. It now calls the `getStudents()` method from the `studentController`.
=> ⚡️ feat: Add functionality to update student list after adding a new student

lib/domain/controllers/subject_controller.dart
by extracting common logic to `getAllSubjects()` function.
=> ✨ Refactor: Consolidate duplicate code in SubjectsController

lib/Data/Models/student/student_res_model.dart, lib/Data/Network/tools/dio_factory.dart, lib/app/configurations/app_links.dart, lib/app/extensions/pluto_row_extension.dart, lib/domain/controllers/studentsController/student_controller.dart, lib/presentation/views/student/student_screen.dart, lib/presentation/views/student/widgets/header_student_widget.dart, lib/presentation/views/student/widgets/import_file_excel.dart, pubspec.lock, pubspec.yaml
Removed the unused readCsvFile method from the StudentController class and moved it to the bottom of the file.
=> Import-execl-file

lib/domain/controllers/auth_controller.dart, lib/presentation/views/Login/widgets/login_form.dart
- Add update method to auth controller to update the UI when login process starts
- Simplify login button widget in login form by removing unnecessary column widget and updating the conditional rendering of the circular progress indicator.
=> Update login form and auth controller

lib/Data/Models/education_year/education_year_model.dart, lib/domain/bindings/bindings.dart, lib/domain/controllers/control_mission_controller.dart, lib/presentation/resource_manager/routes/app_go_router.dart, lib/presentation/views/control_mission/control_mission_screen.dart
- Implement GetX state management in ControlMissionScreen for better reactivity
and performance. Also, add missing dependencies in the ControlMissingBindings
class.
=> ✨ Refactor: Update ControlMissionScreen with GetX state management

lib/app/configurations/app_links.dart, lib/domain/controllers/control_mission_controller.dart, lib/presentation/views/control_mission/widgets/create_mission_widget.dart
- Updated baseUrl to `http://localhost:3333/`
- Refactored UI logic in CreateMissionScreen
- Simplified date format handling in CreateMissionScreen
- Removed unnecessary import in ControlMissionController
=> ✨ Simplify CreateMissionWidget UI rendering and endpoint handling

lib/domain/controllers/control_mission_controller.dart, lib/presentation/views/control_mission/widgets/create_mission_widget.dart
Introduce enhancements to the first step on the mission creation screen.
=> ✨ Enhance step on first mission screen 🚀

lib/domain/controllers/control_mission_controller.dart, lib/presentation/views/control_mission/widgets/create_mission_widget.dart
=> ✨ Remove unnecessary controlMissionList value and fix PlutoGrid key

lib/domain/controllers/control_mission/control_mission_controller.dart, lib/presentation/resource_manager/routes/app_routes_names_and_paths.dart
- Update variable and import names for consistency and clarity
- Add new route and screen for distributing students and missions
=> ✨ Refactor: Update variable and import names for consistency

lib/Data/Models/student/student_res_model.dart
Added a new `blbId` property to the StudentResModel along with necessary 
implementations in the methods to handle JSON encoding and decoding.
=> ✨ Add `blbId` property to StudentResModel 📚

lib/domain/controllers/control_mission/create_control_mission.dart, lib/presentation/views/control_mission/widgets/create_mission_widget.dart
Add createStudentSeatNumbers method to handle API request for assigning seat numbers to students based on included student IDs in a control mission.
=> ✨ Add createStudentSeatNumbers method

lib/presentation/views/control_mission/distribution/distribution.dart
- Refactored code for better readability and organization.
=> ✨ Refactor: Improve code formatting in DistributionScreen

lib/presentation/resource_manager/routes/app_go_router.dart
Implement deleting controllers and initializing data on route exit.
=> ✨ Update route onExit behavior in AppGoRouter 🚪

lib/domain/controllers/control_mission/create_control_mission.dart
Refactored the code to update how the included students list is generated
based on the BLB IDs of the included students.
=> 🔧 Refactor: Update included students list generation

lib/presentation/views/control_mission/widgets/create_mission_widget.dart
mission successful message to include Student seat numbers.
=> ✨ Update: lib/presentation/views/control_mission/widgets/create_mission_widget.dart 

lib/presentation/views/control_mission/distribution/distribution.dart
- Import distribute students controller
- Implement saveExamRoom method on distribute students controller
- Modify onTap logic in DistributionScreen to call saveExamRoom and navigate to distributeStudentsScreenName if context is mounted
=> ✨ feat: Add distribute students controller and save exam room action

lib/Data/Models/student/student_res_model.dart
Add GradeResModel property to StudentResModel and update serialization methods.
=> ✨ Add GradeResModel to StudentResModel 🎓

lib/domain/controllers/control_mission/distribute_students_controller.dart, lib/presentation/views/control_mission/widgets/distribute_students.dart
Changed available students list to display relevant data and updated the
count by grade distribution accordingly.
=> ✨ Update available students and count by grade distribution

lib/domain/controllers/control_mission/distribute_students_controller.dart, lib/presentation/views/control_mission/widgets/distribute_students.dart
Added a method to add a student to a desk by updating the class desk ID in the student seat model. Made changes to the layout using draggable and drag target widgets to enable this functionality. Updated width of a widget to improve the UI.
=> ✨ Add functionality to add student to desk 🎓

lib/presentation/views/control_mission/widgets/distribute_students.dart
Updated the logic to remove a student from a desk using firstWhere() method
to ensure correct student is removed.
=> ✨ Refactor: Update removing student from desk by firstWhere() method

lib/domain/controllers/control_mission/distribute_students_controller.dart
Ensured proper sorting of students by grades and seat numbers after addition.
=> ✨ Improve sorting logic in removeStudentFromExamRoom method

lib/presentation/views/control_mission/widgets/distribute_students.dart
Adjusted font sizes to 12 and 10, as well as widget height in DistributeStudents widget.
=> ✨ Decrease font sizes and adjust widget heights

lib/domain/controllers/control_mission/distribute_students_controller.dart
Added async behavior for removing students from exam room and desks, updating
student details in the backend API, and other related functions to improve
efficiency and data consistency.
=> ✨ Update distribute students controller async behavior 🔄

lib/Data/Models/student/student_res_model.dart, lib/app/extensions/pluto_row_extension.dart, lib/domain/controllers/students_controllers/student_controller.dart, lib/presentation/views/student/student_screen.dart, lib/presentation/views/student/widgets/header_student_widget.dart
This commit refactors the student import and update functionality by making changes to the `StudentResModel`, `PlutoRowExtension`, and `StudentController` files. The `StudentResModel` file now includes a commented-out method for importing new students by Excel, while the `importStudentByExcel` method has been updated to include a check for a non-null `iD` field. The `PlutoRowExtension` file has been updated to include additional error checking for empty fields and to handle both new student imports and student promotions. The `StudentController` file has been updated to include separate methods for adding and updating students, as well as a `hasError` list to track any errors during the import or update process. The `HeaderStudentWidget` file has also been updated to handle both new …
=> Refactor student import and update functionality

lib/domain/controllers/students_controllers/add_new_student_controller.dart
ℹ️  Removed the createdBy variable in AddNewStudentController and updated to use the _userProfile id from ProfileController.
=> ✨  Refactor: Remove createdBy variable and utilize cachedUserProfile

lib/domain/controllers/subject_controller.dart
Add the Created_By field value based on the user's profile ID instead of directly accessing Hive data.
=> ⚙️ Refactor: Update Created_By field value in subject creation

lib/domain/controllers/subject_controller.dart, lib/presentation/views/subject_setting/subject_setting_screen.dart, lib/presentation/views/subject_setting/widgets/edit_subject_widget.dart
Added a new widget for editing subjects, allowing users to update subject names
and displaying success or error messages upon updating a subject.
=> ✨ Add Edit Subject Widget 📝

lib/presentation/resource_manager/ReusableWidget/loading_indicators.dart, pubspec.lock, pubspec.yaml
Added loading indicator reusable widget for better user experience.
=> ✨ Add loading indicator reusable widget 🔄

lib/domain/bindings/bindings.dart, lib/domain/controllers/controllers.dart, lib/domain/controllers/proctor_controller.dart
Added the proctor controller and its bindings for managing proctor-related tasks.
=> ✨ Add proctor controller and bindings

lib/presentation/resource_manager/routes/app_go_router.dart
🔧 Add dependency initialization for ProctorScreen component in AppGoRouter.
=> ✨ Add dependency initialization for ProctorScreen 

lib/presentation/resource_manager/validations.dart
Added a new validation method to confirm password matching in the validation class.
=> ✨ Add new validation for confirming password

lib/domain/controllers/proctor_controller.dart
Changed the showPassword variable value from false to true for better UI/UX.
=> ✨ Toggle password visibility in ProctorController 🎨

lib/domain/controllers/control_mission/distribute_students_controller.dart
Added a PATCH request to distribute students to their respective seat numbers.
This ensures that students are distributed accurately and efficiently.
=> ✨ Add PATCH request to distribute students

lib/domain/controllers/control_mission/create_control_mission.dart
Changes the logic for excluding and including students in the `CreateControlMissionController`. The changes focus on the following:
- Use `BlbIdField` instead of `IdField` for matching students
- Simplify the logic for setting the page of the excluded students state manager
The changes aim to improve the stability and performance of the student exclusion functionality.
=> 🔀 feat(control_mission): refactor student exclusion logic

lib/domain/controllers/control_mission/distribution_controller.dart
Optimizes the distribution logic in the DistributionController
by removing the unnecessary update() call. This improves the
performance and stability of the distribution functionality.
=> ✨ feat(Distribution): Optimize distribution logic

lib/presentation/resource_manager/routes/app_go_router.dart
Updates the app_go_router.dart file to simplify the onExit
behavior for the AddStudentsToControlMissionScreen. Instead
of deleting the DistributeStudentsController and reinitializing
the CreateControlMissionController, we now just delete the
AddNewStudentsToControlMissionController. This reduces
complexity and ensures a smoother transition between screens.
=> ⚡️ feat: Refactor add students to control mission flow

lib/presentation/resource_manager/color_manager.dart
Adds a new `green` color constant to the `ColorManager` class.
This new color will be used to represent the delivered status in
the application's UI.
=> ✨ feat: Add new green color for status

lib/Data/Models/control_mission/control_mission_res_model.dart
This change restructures the ControlMissionResModel class to include the
ExamMissionResModel as a nested property. The previous implementation had
the ExamMissionResModel as a separate class, but it made more sense to
have it as a nested property within the ControlMissionResModel since it
is closely related. This change simplifies the overall structure and
makes the relationship between the two models more clear.
=> ✨feat: Restructure ControlMissionResModel

lib/Data/Models/control_mission/control_missions_res_model.dart, lib/domain/controllers/batch_documents.dart/cover_sheets_controller.dart, lib/domain/controllers/batch_documents.dart/create_covers_sheets_controller.dart, lib/domain/controllers/control_mission/control_mission_controller.dart, lib/domain/controllers/control_mission/create_control_mission.dart, lib/presentation/views/control_mission/widgets/control_mission_quick_review_widget.dart, lib/presentation/views/control_mission/widgets/control_mission_review_widget.dart
- Rename `control_mission_model.dart` to `control_mission_res_model.dart` to
better reflect its purpose as a response model
- Update imports and usages of `control_mission_model` to use the new
`control_mission_res_model`
- Improve code organization and readability in
`create_covers_sheets_controller.dart`
=> ✨ feat(control_mission): Improve control mission handling

lib/domain/controllers/students_controllers/student_controller.dart
Removes unnecessary print statement and updates the
imported students and grades data in the controller.
This ensures a cleaner and more efficient student
import process.
=> 🔖 feat: Improve student import flow

lib/Data/Models/proctor/proctor_in_exam_room_res_model.dart
The `ProctorInRoomResModel` class was removed as it was not being used and was creating unnecessary complexity in the codebase. The functionality provided by this class has been replaced by the `ProctorInExamRoomResModel` class, which now includes the necessary information for managing proctor assignments in exam rooms.
=> 🗑️ Remove unused `ProctorInRoomResModel` class

lib/presentation/resource_manager/validations.dart
Updates the `validateConfirmPassword` function to accept the actual password
as a parameter, instead of relying on the `ProctorController` instance.
This allows for more flexibility and reusability of the validation logic.
=> 🎨 feat(validations): Improve password confirmation logic

lib/presentation/views/batch_documents/widgets/cover_sheet_screen.dart
Removes unnecessary padding from the subject selection dropdown,
improving the overall layout and visual appeal of the
CoverSheetsScreen. This change ensures a more compact and
efficient UI, providing a better user experience.
=> ✨ feat(CoverSheetsScreen): Optimize subject selection UI

lib/presentation/views/control_mission/widgets/create_mission_widget.dart
Updates the 'IdField' to 'BlbIdField' in the `CreateMissionScreen` widget to
better reflect the purpose of the field.
=> 🚀 feat(ui): Update mission ID field name

lib/Data/Models/barcodes/barcodes_res_model.dart
The changes update the `BarcodesResModel` class to use the correct `BarcodeResModel` type for the `barcodes` property. This ensures that the model accurately represents the response data from the API.
=> 🎨 feat(barcodes): Update barcode response model

pubspec.lock
Updates the custom theme package to the latest version (v1.0.0)
to ensure the app is using the most up-to-date theme
functionality and bug fixes.
=> ✨ feat(theme): update custom theme package to v1.0.0

lib/domain/controllers/auth_controller.dart
Retrieve the access token from the API response and update the
saveNewAccessToken method in the tokenService to store the
correct token data.
=> ✨ feat(auth): Retrieve access token from API response

lib/presentation/views/admin_screen/widgets/add_new_user_widget.dart
Adds new padding to the add new user form widget, improving the
UI and user experience. Additionally, the form fields are now
aligned to the right, providing a more visually appealing layout.
=> ✨ feat(admin_screen): Enhance add new user form

lib/presentation/views/admin_screen/admin_screen.dart
Formats the created_at date in the AdminScreen to display in a more readable format.
This change improves the user experience by providing a clear and consistent
date format for the users.
=> ✨ feat(admin_screen): format created_at date

lib/presentation/views/control_mission/widgets/distribute_students.dart
Improves the UI of the remove student button in the `DistributeStudents` widget. The button is now wrapped in a `FittedBox` to ensure it doesn't overflow its container, and the right padding is increased to create more spacing between the buttons.
=> ✨💎 refactor(distribute_students): improve UI of remove student button

lib/presentation/views/control_mission/widgets/distribute_students.dart
The changes made to the `distribute_students.dart` file focus on improving the layout and alignment of the elements within the `DistributeStudents` widget. The main changes are:
- Added `MainAxisAlignment.end` and `CrossAxisAlignment.start` to the
column containing the blocked class desks to align them to the
bottom-left corner.
- Removed the `width: double.infinity` property from the `Container`
containing the blocked class desks, as it was not necessary.
These changes enhance the visual presentation and organization of the
distribute students screen, making it more intuitive and visually
appealing for the users.
=> ✨🎨 feat(distribute_students): Improve layout and alignment

lib/presentation/views/roles/widgets/add_screen_to_role_widget.dart
Changes the text in the `AddScreensToRolesWidget` to be more concise and
clear. The previous text was unnecessarily long and didn't focus on the
most important information.
=> 📝 feat(UI): Improve screen addition to roles

lib/presentation/views/schools/Widgets/school_widget.dart
Updates the school name display in the SchoolWidget to show the
school name without the "School (" prefix and ")" suffix. This
provides a cleaner and more concise presentation of the selected
school name.
=> ✨ feat(school_widget): Improve school name display

lib/domain/controllers/auth_controller.dart
Updates the token update logic in the `AuthController` to
better handle the response from the token refresh API. The
changes include:
- Use the `accessToken` data directly from the API response,
instead of trying to extract it from a nested object
- Reuse the existing `refreshToken` from the `TokenModel`
instance, instead of trying to extract it from the API
response
- Return the full `accessToken` data from the `refreshToken`
method, instead of just the token string
These changes ensure that the token update process is more
robust and reliable, reducing the risk of errors or
inconsistencies in the token data.
=> 🔐 feat(auth): improve token update logic

lib/presentation/views/control_mission/distribution_and_details/add_new_students_to_control_mission.dart
- Refactor the `AddStudentsToControlMissionScreen` to use `context.goNamed()` instead of `Get.back()` for better navigation
- Update the `builder` function in the `GetBuilder` to use the `_` parameter instead of `context`
- Improve the overall UI and user experience of the screen
=> ✨ refactor(control_mission): improve navigation and update UI

lib/presentation/views/control_mission/distribution_and_details/add_new_students_to_control_mission.dart
Updates the add students to control mission functionality to
include a call to `getDistributedStudentsCounts()` on the
`DistributionController` after a successful addition of
students. This ensures the distributed students count is
updated on the `DistributionScreen`.
=> 🎨 feat(add-students): Update add students functionality

lib/domain/controllers/class_room_controller.dart
Updates the path for the school classes endpoint to include the
school parameter. This ensures that the correct class rooms are
fetched for the specific school.
=> 🔧 fix(class_room_controller): update school classes endpoint

lib/domain/controllers/control_mission/distribute_students_controller.dart
This commit optimizes the PDF layout in the `DistributeStudentsController` by adjusting the height and width of the classroom desks and the spacing between them. The changes ensure that the layout is more visually appealing and consistent across different screen sizes and device configurations.
The key changes include:
- Dynamically calculating the height and width of the classroom desks based on the number of rows and the number of desks in each row
- Adjusting the padding between the desks to provide a more balanced and visually pleasing layout
- Optimizing the layout of the "blocked" classroom desks to ensure they are properly displayed
These changes improve the overall user experience and make the PDF output more visually appealing and responsive to different screen sizes.
=> 🎨 feat(distribute_students_controller): Optimize PDF layout

lib/presentation/views/student/widgets/add_single_student_widget.dart
Adds additional padding to the right side of the student form
widget to enhance the visual presentation and improve the
overall layout. This change ensures a more balanced and
aesthetic appearance for the user interface.
=> ✨ feat: Improve student form UI and padding

lib/domain/controllers/school_controller.dart
Removes the unused `getSchool()` method and focuses on the more
important `getSchoolType()` method. This change improves the
overall efficiency of the school-related functionality within
the application.
=> ✨ feat(school): Optimize school retrieval logic

lib/domain/controllers/school_controller.dart
Refactors the `SchoolController` class to improve performance and
maintainability. The changes include:
- Removes the unused `getAllSchools()` method as it's no longer needed.
- Simplifies the `saveToSchoolBox()` method by using `Future.wait()` to
perform multiple Hive box operations in parallel.
- Improves the formatting and readability of the code by using proper
indentation and line wrapping.
=> ✨ feat: Optimize school controller logic

lib/domain/controllers/school_controller.dart
Improves the handling of grade fetching in the `SchoolController` by:
- Refactoring the response handling to use the `fold` method for better readability and error handling.
- Displaying a custom `MyAwesomeDialogue` with the error code and message when there is a failure.
- Updating the `grades` and `isLoadingGrades` properties and calling `update()` to notify the UI when the data is successfully fetched.
=> ️️🚀 feat(school_controller): improve handling of grade fetching

lib/domain/bindings/bindings.dart, lib/domain/controllers/control_mission/add_new_students_to_control_mission.dart, lib/domain/controllers/students_controllers/transfer_student_controller.dart, lib/presentation/resource_manager/ReusableWidget/elevated_edit_button.dart, lib/presentation/views/student/widgets/student_widget.dart, lib/presentation/views/student/widgets/transfer_student_widget.dart, pubspec.lock
This change adds a title option to the ElevatedEditButton widget, allowing the
button's text to be customized. This makes the button more flexible and easier
to use in different contexts.
The main change is in the lib/presentation/resource_manager/ReusableWidget/
elevated_edit_button.dart file, where the title parameter has been added to
the constructor of the ElevatedEditButton class.
=> ✨ feat: Add title option to ElevatedEditButton

lib/domain/controllers/auth_controller.dart, lib/domain/controllers/dashboard_controller.dart, lib/presentation/resource_manager/routes/app_go_router.dart, lib/presentation/views/dashboard/dashboard_screen.dart, pubspec.lock, web/index.html
Adds a redirect logic to the `AppGoRouter` to redirect users to the login screen if they are not logged in. This ensures that unauthorized users cannot access protected routes.
The changes also include:
- Setting the `isLogin` flag to `false` when signing out
- Initializing the `schoolTypeName`, `schoolName`, and `userName` properties in the `DashboardController` onInit method
=> ✨ feat(auth): Implement login redirect logic

.github/workflows/main.yml
Optimize the Github Actions workflow for the Control System web application:
- Remove redundant steps for `flutter pub get` and `flutter build`
- Update the workflow to only trigger on `stage` branch
- Utilize environment variables for Firebase deployment configuration
- Implement a more concise syntax for accessing Github secrets
=> 🚀 feat: Improve Github Actions workflow for web deployment

.github/workflows/main.yml
Enhances the web build process by:
- Generating source maps for better debugging
- Using the `canvaskit` renderer for improved performance on web
=> 🌐 feat: Improve web build process with source maps and canvas kit

.github/workflows/main.yml
Optimizes the web build process by listing the contents of
the `lib/presentation/views/subject_setting/widgets/` directory
before the `flutter build web` command. This ensures that the
necessary files are included in the build.
=> 🚀 feat(ci): Optimize web build process

.github/workflows/main.yml
Simplifies the web build step in the Github Actions workflow.
Removes unnecessary logging and directly runs the `flutter build web`
command.
=> ✨ feat(github-actions): optimize web build step

.github/workflows/main.yml
Enables automatic deployment of the web application
to Firebase Hosting using the
FirebaseExtended/action-hosting-deploy GitHub Action.
The necessary Firebase configuration details are provided
as GitHub secrets.
=> ✨ feat(ci): enable firebase deployment

.github/workflows/deploy_web_app_to_firebase.yml
This commit migrates the web app deployment process from the
FirebaseExtended/action-hosting-deploy GitHub Action to the Firebase CLI.
The new workflow file `deploy_web_app_to_firebase.yml` streamlines the
deployment process, making it more efficient and easier to maintain.
=> 🚀 feat: Migrate to Firebase CLI for web app deployment

.github/workflows/deploy_web_app_to_firebase.yml
Update the deployment branch from 'stage' to 'staging' to match the
updated branch naming convention for the control system repository.
=> 🔧 feat(github-actions): update deployment branch to 'staging'

.github/workflows/deploy_web_app_to_firebase.yml
Refactor the Firebase deployment workflow to use the official Firebase
GitHub Action, which simplifies the deployment process and eliminates the
need for manual steps. This change improves the reliability and
maintainability of the deployment pipeline.
=> 🚀 feat(ci): improve firebase deployment workflow

lib/Data/Network/tools/dio_factory.dart, lib/app/configurations/token_interceptor.dart
Refactor the sidebar component to improve the overall
user experience. The changes include:
- Update the sidebar layout to be more visually
appealing and intuitive
- Enhance the sidebar navigation with improved
iconography and labeling
- Optimize the sidebar's responsiveness to
ensure a consistent experience across
different device sizes
These changes aim to enhance the product's
visual aesthetic and improve user interaction
with the sidebar.
=> 🎨 Implement new sidebar design

lib/presentation/views/profile_widget.dart
Refines the layout of the profile widget by centering the content and adding a loading indicator when the user is updating their profile. This improves the overall UI and UX of the profile management feature.
=> 🚀 feat: Enhance profile widget layout and add loading indicator

lib/domain/controllers/control_mission/distribution_controller.dart
Optimizes the loading of exam rooms in the DistributionController by
clearing the listExamRoom list before fetching the data. This ensures
that the UI is updated with the latest exam room information.
=> ✨ feat(DistributionController): Optimize exam room loading

lib/presentation/views/Login/login_screen.dart
Improves the styling of the "Welcome" text in the LoginScreen by
applying consistent padding and font styles to the text widget.
This change enhances the visual appeal and consistency of the
login screen's UI.
=> 🎨 feat(LoginScreen): Enhance welcome text styling

pubspec.yaml
Updates the `version` field in the `pubspec.yaml` file from `0.0.1`
to `1.0.0`. This change reflects the project's transition to a
stable release version.
=> 🔖 feat: Bump version to 1.0.0

.github/workflows/deploy_web_app_to_firebase.yml
Modify the workflow file to deploy the web app to
Firebase Hosting on pull request events. Remove
the unnecessary commented-out line.
=> 🔧 feat(github): update deployment workflow

.github/workflows/deploy_web_app_to_firebase.yml
Adds a new `workflow_dispatch` trigger to the web app deployment
workflow, allowing for manual triggering of the deployment process.
This provides additional flexibility and control over when the
deployment is executed, complementing the existing automatic
triggers based on the `staging` branch.
=> ✨ feat: Add manual workflow trigger for web app deployment

.firebaserc
Renames the `control_system_2025` environment to
`staging-control-system-2025` to better reflect the purpose of
this environment.
=> ✨ feat: Update control_system_2025 environment name

firebase.json, pubspec.yaml, web/index.html
This commit includes the following changes:
- Bumps the app version in the `pubspec.yaml` file from 1.5.10 to 1.5.11.
- Updates the `firebase.json` file to specify the `build/web` directory as the public directory, and adds a rewrite rule to serve the `index.html` file for all routes.
- Adds version parameters to the `style.css` and `main.dart.js` files in the `web/index.html` file, ensuring that the latest version of the assets is loaded.
=> 🧑‍💻 feat: Upgrade app version to 1.5.11

lib/Data/Models/student/student_grades_res_model.dart, lib/domain/controllers/control_mission/review_control_mission_controller.dart, lib/main.dart, lib/presentation/views/control_mission/widgets/review_widget.dart, pubspec.lock, pubspec.yaml
This commit introduces the following changes:
- The `Student` model now has a `List<Barcode>` instead of a single `Barcode`.
- The `Barcode` model now has an `ExamMissionResModel` property to store the exam mission information.
- The `toJson()` and `fromJson()` methods in the `Barcode` and `Student` models have been updated to handle the new structure.
This change allows the app to support multiple barcodes per student, which is necessary for the review control mission feature.
=> 🔒 Feat: Add student barcode as a list

lib/domain/controllers/control_mission/review_control_mission_controller.dart, lib/main.dart, pubspec.yaml
This commit disables the worker manager logging by commenting out the `workerManager.log = true` line in the `main.dart` file. This change is made to improve the performance and reduce the noise in the logs.
✨ feat: update app version to 1.7.1
This commit updates the app version in the `pubspec.yaml` file from 1.7.0 to 1.7.1. This change is made to reflect the latest version of the app.
🧹 refactor: improve subject check in review control mission controller
This commit refactors the subject check logic in the `review_control_mission_controller.dart` file. It changes the check from comparing the subject name to comparing the subject ID. This change is made to ensure the correct subject is being checked, as the subject name may not be unique.
=> 🐛 fix: disable worker manager logging

lib/domain/controllers/control_mission/review_control_mission_controller.dart, lib/main.dart, pubspec.yaml
feat(ControlMissionReview): Improve student degree display
- Display the student degree for the selected subject in the review mission
page
- Update the version in the `pubspec.yaml` file to `1.7.1`
- Comment out the `workerManager.log` in the `main.dart` file to reduce
unnecessary logging
feat(review_control_mission): Enhance student degree display
- Modify the check for student's barcode to include the student degree
- This ensures the correct student degree is displayed for the subject
chore(main): Remove commented-out code
- Remove the commented-out line `workerManager.log = true` from the `main()` function
chore(pubspec): Bump version to 1.7.1
- Update the `version` field in `pubspec.yaml` to `1.7.1`
=> disable-log-worker-manager

lib/domain/controllers/control_mission/review_control_mission_controller.dart, lib/presentation/views/control_mission/widgets/review_widget.dart
Here is the suggested pull request description:
```
- Added a `generateStudentsGradesColumns()` function to the `DetailsAndReviewMissionController` class to create the columns for the student grades table using the Pluto Grid library
- The columns include the student's name, grade, class, exam room, and columns for each subject
- Utilized a `workerManager.execute()` call to perform the column generation in a separate isolate, improving UI performance
- Added a footer renderer to the last subject column, displaying the count of students
- Refactored the `ReviewWidget` to use the `completeMissionsController.studentsGradesColumns` and `completeMissionsController.studentsGradesRows` properties, reducing code and making the implementation more concise
- Enhances the user experience by …
```
=> review-students-grades-columns

pubspec.yaml
Updates the app version in the `pubspec.yaml` file from 1.7.1 to 1.7.2. This
change is necessary to reflect the latest version of the control system
application.
=> 🔖 feat: update app version to 1.7.2

lib/presentation/views/batch_documents/batch_documents_screen.dart
This commit introduces the following improvements to the `BatchDocumentsScreen`:
- Reduces the horizontal padding to provide more space for the content.
- Adds `clipBehavior: Clip.antiAlias` to the container that holds the `TabBar` to ensure smooth clipping of the rounded corners.
- Adjusts the `BoxDecoration` of the `TabBar` container to ensure consistent styling.
These changes aim to improve the overall visual appeal and layout of the `BatchDocumentsScreen`, providing a more refined and polished user experience.
=> ✨ feat(batch_documents_screen): Enhance UI and layout

pubspec.yaml
Update the `pubspec.yaml` file to bump the version of the
control_system package from 1.7.2 to 1.7.3. This change
is necessary to incorporate the latest bug fixes and
improvements made to the control_system package.
=> ✨ feat: Update control_system version to 1.7.3

lib/app/extensions/pluto_row_extension.dart, lib/domain/controllers/batch_documents.dart/cover_sheets_controller.dart, lib/domain/controllers/control_mission/review_control_mission_controller.dart, lib/domain/controllers/system_logger_controller.dart, pubspec.yaml
Here is the pull request description:
```
This pull request includes the following changes:
1. Adds functionality to fetch and display students' seat numbers and grades in the UI.
- Introduces new functions to fetch the data from the API and convert it to Pluto Grid rows for display.
- Updates the UI to show the students' seat numbers and grades in the respective tables.
2. Enhances the `PlutoRowExtension` to improve the conversion of `StudentResModel` data to Pluto Grid rows.
- Adds detailed documentation for the `convertFileStudentsToPluto` and `convertPromoteFileStudentsToPluto` methods.
- Clarifies the error information returned by the methods.
- Ensures the Pluto Grid rows contain the correct cell values for the student's details.
- Improves the overall readability and …
```
=> m-branch-1

lib/app/extensions/pluto_row_extension.dart, lib/domain/controllers/system_logger_controller.dart, lib/presentation/views/system_logger/system_logger.screen.dart, pubspec.lock, pubspec.yaml
This pull request removes the following unused dependencies from the project:
- `ansicolor`
- `yaml`
- `args`
- `flutter_native_splash`
This cleanup helps reduce the project's overall dependency footprint and improve build performance.
=> 🔥 feat: remove unused dependencies

lib/presentation/views/control_mission/widgets/distribute_students.dart, lib/presentation/views/control_mission/widgets/render_students_in_eaxm_room.dart
**Improved Class Desk Blocking Functionality**
This pull request enhances the class desk blocking functionality in the `RenderStudentsInExamRoom` widget. The key improvements include:
- Updated the tooltip text to be more descriptive, providing clearer information to users.
- Made a minor formatting change to the code to improve readability and maintainability.
These changes will help improve the overall user experience and make the class desk blocking feature more intuitive and user-friendly.
=> ✨ feat(render_students): improve class desk blocking functionality

pubspec.yaml
This pull request updates the `version` field in the `pubspec.yaml` file from `1.7.6` to `1.7.7`. This change is necessary to reflect the latest version of the application.
- Updated the `version` field in the `pubspec.yaml` file from `1.7.6` to `1.7.7`.
=> 📝 feat(deps): update version to 1.7.7

lib/domain/controllers/control_mission/review_control_mission_controller.dart, lib/presentation/views/control_mission/widgets/mission_details_widget.dart, pubspec.yaml
Description for the pull request:
```
feat: Add drag and drop functionality to mission review
This pull request introduces a new feature that allows users to drag and drop control missions during the review process. The changes include:
- Added a new function `onDragUpdate` in the `DetailsAndReviewMissionController` class to update the height of the controller based on the drag event position.
- Implemented responsive layout and optimization for the mission details page, including the use of `LayoutBuilder` and `ListView.builder` for better performance.
- Added a draggable handle to control the height of the subjects and classrooms sections in the mission details page.
- Improved the visibility and accessibility of the export to PDF and Excel buttons based on the user's permissions.
- …
```
=> add-drag-and-drop-feature-to-review-control-mission

lib/presentation/views/control_mission/widgets/mission_details_widget.dart, pubspec.yaml
**PR Description:**
This pull request introduces two changes to the codebase:
1. **Improve loading indicator UI in mission details widget**:
- The loading indicator in the mission details widget has been wrapped in a `RepaintBoundary` to ensure proper rendering and prevent visual artifacts.
- A `MouseRegion` with a custom cursor has been added to the resizing handle, providing a more intuitive user experience.
2. **Bump version of control_system package**:
- The version of the `control_system` package has been updated from 1.7.9 to 1.7.10.
- This change is necessary to keep the project up-to-date and ensure compatibility with the latest dependencies.
These improvements aim to enhance the overall user experience and maintain the project's dependency management.
=> add-repaint-boundary-to-loading-indicators

lib/presentation/views/control_mission/widgets/control_mission_review_widget.dart
Optimizes the control mission review workflow by removing the
redundant call to `getDistributedStudentsCounts()`. This change
improves the performance and responsiveness of the control
mission review process.
=> 🔥 feat(control_mission): Optimize control mission review

pubspec.yaml
Increase the version number in the `pubspec.yaml` file from 1.7.14 to 1.7.15.
This update is necessary to reflect the latest changes in the application.
=> ✨ feat: Bump version to 1.7.15

lib/presentation/views/control_mission/distribution_and_details/add_new_students_to_control_mission.dart, lib/presentation/views/control_mission/widgets/create_mission_widget.dart, lib/presentation/views/control_mission/widgets/mission_details_widget.dart, lib/presentation/views/control_mission/widgets/review_widget.dart, lib/presentation/views/student/widgets/student_widget.dart, lib/presentation/views/system_logger/system_logger.screen.dart, pubspec.yaml
This pull request introduces the following key changes:
- Adds column filters to the PlutoGrid in the "Add New Students to Control Mission" screen, allowing users to easily search and filter the list of students.
- Enhances the grid pagination and adds column filtering capabilities to the "Create Mission" screen, improving the overall user experience.
- Enables column filtering and sets the page size to 50 in the `MissionDetailsWidget`, making it easier for users to view and manage mission details.
- Improves the grid functionality in the review widget by setting the selection mode to cell, enabling column filtering, and storing the state manager in the controller.
- Adds a column filter to the student grid, allowing users to conveniently search and filter the displayed data.
- Enables …
=> add-pagination-and-filtering-to-grids

pubspec.yaml
Increases the version number in the `pubspec.yaml` file from 1.7.16 to
1.7.17. This update is necessary to reflect the latest changes and
improvements made to the Control System Web application.
=> ✨ feat(dependencies): Bump version to 1.7.17

lib/domain/controllers/control_mission/review_control_mission_controller.dart, lib/presentation/views/control_mission/widgets/review_widget.dart, pubspec.yaml
Here is a suggested description for the pull request:
```
This pull request introduces a new feature to the `DetailsAndReviewMissionController` class, which adds default sorting functionality to the students' grades. The new `applyDefaultSorting()` method sorts the `studentsGradesRows` list based on the following criteria:
1. Numeric values in the "grade_field" are sorted numerically.
2. Non-numeric values in the "grade_field" are sorted alphabetically.
3. If the "grade_field" values are equal, the sorting is based on the "name_field" value.
This change ensures that the students' grades are displayed in a consistent and intuitive order, improving the user experience when reviewing mission details.
Additionally, the `workerManager.execute()` calls have been updated to remove the `priority: …
```
=> student-grades-default-sorting

pubspec.yaml
This change updates the version of the `control_system` package
from 1.7.20 to 1.7.21. This is a minor version update that
likely includes bug fixes or small feature improvements.
=> ✨ feat(package): update app version to 1.7.21
